### ISSUE TITLE
problem with midi connections from within shortcuts-midi

### ISSUE THREAD

**Issue by ewanuno** [rncbc/qtractor#10]
when i open the inputs or outputs window from the shortcut editor, the midi connections window is drawn below the current window and cannot be used. switching to the midi connections window isn't possible because focus returns to the shortcuts/midi window.

**Comment by rncbc** [comment]
On 01/13/2016 04:39 PM, ewanuno wrote:
> when i open the inputs or outputs window from the shortcut editor, the
> midi connections window is drawn below the current window and cannot be
> used switching to the midi connections window isn't possible because
> focus returns to the shortcuts/midi window
>

hi. you're holy right. great finding. indeed.

now... maybe it suffices to make qtractorShortcutsForm modeless (ie. not 
modal)...let's try...done.

qtractor v0.7.3.7+
   https://github.com/rncbc/qtractor/commit/6b339e8

test && tell
-- 
rncbc aka. Rui Nuno Capela
