### ISSUE TITLE
Feature request: Improved listing of presets and automation

### ISSUE THREAD

**Issue by thebutant** [rncbc/qtractor#104]
When using plugins with lots of presets (for instance TAL NoizeMaker) or lots of automation possibilities (for instance U-he's Zebra2), the list of options continue outside of my screen.
Especially when using a small computer.
And as far as I can see, I have no way of accessing the part of the list that's on the right side of my screen. Well, with the cursors I can actually access the presets or automation settings, but I cannot see which one I'm accessing.

So a feature request would be a way of scrolling further when the screen is full.

Was this possible to understand?

**Comment by rncbc** [comment]
yes, i do understand, but then, the issues don't quite relate to qtractor code itself but to a native widget style or theme if you prefer instead.- it's all a matter of how the popup menus are spread out in the screen, some styles are better fit to small screens, others not so much. It's quite a jungle out there :)

**Comment by thebutant** [comment]
Ah, I see.
I didn't even think of that. I simply haven't met the issue in any other application, but have been having it in Qtractor on any OS and any DE (which are maybe only 3) I've used the last few years.

My main machine is a 15" 1920x1080 running Cinnamon as a DE. And the presets in Noize Mak3r just about fill up the screen. On the 13" computer I also use frequently, the presets continue on the right side of the screen. The automation possibilities in Zebra2 go far out of my screen on any computer. Amsynth's presets do the same, but there you can luckily change presets by right clicking on the GUI.

This is no big issue, it's just a small one I stumble upon now and then. And it seems a bit. . . computing in the 90's, if you see what I mean. It's one of those things that rarely happen anymore - something going on outside of your screen and there's no way you can't reach it.

But if it's not even in your hands, then I won't complain. Not that I'd complain anyway, as much as I love this software and appreciate you making it. 
At least now you know that this is happening on quite a few systems.
