### ISSUE TITLE
Feature request: Add navigating between tracks to shortcut menu

### ISSUE THREAD

**Issue by simonvanderveldt** [rncbc/qtractor#106]
Hi Rui,

I have a small feature request. Whilst I can already navigate between tracks using the arrow keys on my keyboard I was wondering if that action can be added to the shortcut menu.
I'm asking this for two reasons:
- The up/down arrows only work once you've first selected a track. When no track is selected they scroll the track widget. If one has dedicated buttons mapped to next/previous track they will always work.
- I'd like to use my MIDI controller to navigate between tracks and the shortcut menu allows one to map any command to a MIDI message (which is awesome btw!)

What do you think?

**Comment by rncbc** [comment]
hi, i believe it's been always there: see main menu Track > Navigate > First, Next, Previous, Last, None.
hth
cheers

**Comment by simonvanderveldt** [comment]
Thanks for the quick response! You're right, they are there and also available in the shortcuts menu. I totally missed them because I was looking for `//Track/Navigate/Next` and `//Track/Navigate/Previous`, but they can be found under `//Edit/Track/Navigate/Next` and `//Edit/Track/Navigate/Previous`.
I wasn't aware the whole `Track` menu item was duplicated under the `Edit` menu. Is this on purpose?

**Comment by rncbc** [comment]
> I wasn't aware the whole `Track` menu item was duplicated under the `Edit` menu. Is this on purpose?

yes, it is ;)

**Comment by simonvanderveldt** [comment]
OK, good to know :)
Thanks again for the help!
