### ISSUE TITLE
Shortcuts using Midi CC value 0 and 127 don't work/work incorrectly

### ISSUE THREAD

**Issue by simonvanderveldt** [rncbc/qtractor#108]
Hi Rui, going forward based on your info from #106 I tried mapping `//Edit/Track/Navigate/Previous` and `//Edit/Track/Navigate/Next` to two different midi CCs (CC 14 and 15 to be precise).
I noticed that the following two cases don't really work:
- A value of 0 doesn't result in an action.
- A value of 127 only works once, the next time it's sent nothing happens.

Any value in the range 1-126 (including 126) does work.

Is this correct behavior? A value of 0 resulting in no action might be intended, but 127 only working once doesn't seem correct to me.

**Comment by rncbc** [comment]
it might be correct behavior, because you're trying to use a continuous/scalar controller value (a rotary/slider knob?) to actuate over a toggle/on-off subject. So that perhaps only changes in value do trigger the action.

**Comment by simonvanderveldt** [comment]
No, I'm using a button that on every press sends whatever I set it to. So I have the following situations:
- Set the button to send value=0, nothing happens
- Set the button to send value=127, it only works once
- Set the button to send value=1 or 2 or ... or 126, it always works

**Comment by rncbc** [comment]
if you can configure the button at all, please make it a toggled one, sending value=0 (OFF) and value=127 (ON) in alternation, that i think is the usual way buttons work :)

i might be short-sighted but letting a button to always send one fixed and constant value, whenever you press/depress it, is kind of a "stupid" setting to have--blame on the device not you nor me ;)

and please, don't you tell me about that stateless/restful control model if you're thinking on that...
let me tell this is no web service at all: this is about a plain old stateful control model: both ends are supposed to keep their own state, being either a physical/external controller/actuator (a knob, slider, button, whatever) and then the other end, the receiver (re)actor (qtractor in this case) -- both ends' state should match, at sometime, somehow, and eventually :)

hth
cheers

**Comment by simonvanderveldt** [comment]
> if you can configure the button at all, please make it a toggled one, sending value=0 (OFF) and value=127 (ON) in alternation, that i think is the usual way buttons work :)

When doing that it actually triggers the command twice, the first time for the press (value = 127) and the second time for the release (value = 0).

Qtractor already behaves the way I expected it to (trigger the shortcut action on value receive) for values 1-126, just not for 0 and 127, so it seems like bug in handling those values to me.

**Comment by rncbc** [comment]
not quite a bug but yes it's fringe/corner bug of sorts.. whatever :)
it might have to do with some one-shot/triggering semantics to shortcuts in particular: something I've been chalking as same as a latched (ie. non-momentary) type of control actuator and that was probably way too naive or kinda wrong doing :/
ok. maybe a new special triggering mode should be on demand here, special only for shortcuts maybe, may a so called "one-shot" perhaps?
moving on up, into the next development cycle though
cheers && thanks

**Comment by simonvanderveldt** [comment]
I think this can be the simplest implementation possible, in pseudo code: If message that matches shortcut comes in trigger the shortcut, the actual value of the message can be ignored.
Don't think it would need anything more complex, right?

**Comment by rncbc** [comment]
yes, except to shortcuts that are of the checkable/toggled kind...

**Comment by rncbc** [comment]
ok. the first fix is in qtractor-0.8.5.3git. https://github.com/rncbc/qtractor/commit/7df581

cheers && thanks

**Comment by simonvanderveldt** [comment]
Thx! I'll give it a try this weekend.

Regaring the MIDI mappings in general: I was wondering what the expected behavior for all MIDI mappable actions is.
For example the MIDI mappings one can make in the Controllers view for Solo, Mute, etc seems to expect a "toggle" type value (0 for off, 1-127 for on) to be sent. This means the device that sends the MIDI messages needs to keep state as well.
Is this the way those mappings are supposed to work? Wouldn't it be nice(r) if the MIDI controller could just send a CC message and Qtractor would toggle the state?

**Comment by rncbc** [comment]
as of this commit above (qtractor >= 0.8.5.3git. https://github.com/rncbc/qtractor/commit/7df581), the so called "one-shot" behavior is now in place for all action shortcuts, making a MIDI controller's device state/value *irrelevant* for actually triggering the mapped action.

all other mappings (not related to *one-shot* shortcuts) still honor the state and/or value on either or both ends as before and always, so that if you want to control a toggle subject (eg.  Solo, Mute, etc.) with a *momentary* controller (eg. key, pad, foot-switch, etc.) you'll probably need to un-check the so called **Latch**  mode of operation ;)

hth.
cheers

**Comment by simonvanderveldt** [comment]
> as of this commit above (qtractor >= 0.8.5.3git. 7df581), the so called "one-shot" behavior is now in place for all action shortcuts, making a MIDI controller's device state/value irrelevant for actually triggering the mapped action.

Can confirm this works. One can send any CC value (0-127) for the CC as configured in shortcuts and it works. Awesome! Thanks for the quick fix!

> all other mappings (not related to one-shot shortcuts) still honor the state and/or value on either or both ends as before and always, so that if you want to control a toggle subject (eg. Solo, Mute, etc.) with a momentary controller (eg. key, pad, foot-switch, etc.) you'll probably need to un-check the so called Latch mode of operation ;)

Now that you mention it, could it be this behaviour is/was caused by the "Latch" option being enabled by default for one-shot shortcuts. Shouldn't "Latch" be off for them?
![image](https://user-images.githubusercontent.com/204286/34320936-ce378d74-e803-11e7-841b-61d4755e2fce.png)

**Comment by rncbc** [comment]
> could it be this behaviour is/was caused by the "Latch" option being enabled by default for one-shot shortcuts. Shouldn't "Latch" be off for them?

could be but "Latch" is disabled/grayed out anyway for shortcut actions :) 
so...

**Comment by simonvanderveldt** [comment]
> could be but "Latch" is disabled/grayed out anyway for shortcut actions :)
> so...

Yeah, that's true, but even though it's grayed out it's showing the checkbox as checked. Whereas the checkbox for "Logarithmic" is shown as unchecked. This seems to suggest that even though the user can't change the value it's actually enabled for "Latch".
If that's the case I guess it would be cleaner to fix the issue by getting rid of the "Latch" = enabled setting for oneshot controls?

**Comment by rncbc** [comment]
> I guess it would be cleaner to fix the issue by getting rid of the "Latch" = enabled setting for oneshot controls?

maybe now in 0.8.5.7git. https://github.com/rncbc/qtractor/commit/9ac6c3 ;)

byee

**Comment by simonvanderveldt** [comment]
Looks and works good!
One (hopefully final :P) question, shouldn't the "Latch" option for non-oneshot options be user changeable? It used to be before this change.
![image](https://user-images.githubusercontent.com/204286/34323309-da70ea2e-e842-11e7-9f83-a7e232c1a85c.png)

**Comment by rncbc** [comment]
and is is, only not for shortcuts, where it's disabled but checked for toggling subjects, unchecked otherwise.

subtle uh? :)

**Comment by simonvanderveldt** [comment]
> and it is, only not for shortcuts, now made as one-shot with Latch option disabled but checked for toggling subjects and unchecked otherwise.

But that means the user can no longer choose to either use a latching or a non-latching/momentary switch with toggling shortcuts (like Track mute), which means a regression for people using MIDI footswitches for example, right?

**Comment by rncbc** [comment]
well, yes probably, but for those cases I would not recommend to use action Shortcuts--which are all now one-shot type, ok?--there are other and better ways to map a MIDI controller into those  controllable/automatable subjects, remember? that said, menu shortcuts might not be always the most sane to be mapped actuated by a "momentary" controller device (one that sends the same message type but toggling value when is pressed _and_ depressed).
byee && merry xmas

**Comment by simonvanderveldt** [comment]
Since I'd like to start contributing back to Qtractor I thought this would be a good opportunity to dive into the code and see if I could understand how it's working and come up with something that works for all use cases.
I have something that works for me for both one-shot as well as toggleable shortcuts and for both latching and non-latching controllers for those toggleable shortcuts.

@rncbc Since I don't know if this is OK with you and if you're open to contributions I haven't made a PR. The commit is here with some annotations about why/how I did things and questions I still have.
https://github.com/simonvanderveldt/qtractor/commit/e43191498ed0dc34209802b7516ceb7370ac29dc
What do you think?

**Comment by rncbc** [comment]
hi, you can certainly make it a PR, a couple of notes though:
- the "Latch" setting is "true" on MidiControlObserver::ctor because it is the usual mode on most MIDI controller devices that I know of; the non-latch/momentary ones seem to be rare out there, but that's not a real issue or is it?
- "one-shot" shortcuts (ActionControl::MidiObserver) in fact were just being flagged as such by having both "Integer" and "Latch" attributes set to "true";
your proposed commit seem to overrule both of the above, and makes me think whether it's neutral to other modes of controllers but plain ""one-shot" and toggled" ones.
note also that I've done no field-tests, i'm just guessing
cheers
