### ISSUE TITLE
Trying to use Helm VST is crashing Qtractor

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qtractor#109]
Qtractor 0.8.5, helm 0.9

On a MIDI track, loading Helm LV2 in Qtractor works as expected.

Trying to load helm-VST in Qtractor, and the Helm windows is kind of flickering (it does look that Helm's GUI is switching endlessly between the different presets), then Qtractor's CPU usage is rising up quickly above 100%, then Qtractor is staying frozen-ish for around a minute, Helm's GUI look to become stable (CPU is still over 100%), and eventually, it crashes.

Note that strangely, if I relaunch then Qtractor and try to add Helm to a MIDI track, then there is a second "Helm" in the plugin box:
![helm-qtractor](https://user-images.githubusercontent.com/8705846/34266111-62e49f12-e678-11e7-8d62-954871e7f6e9.png)
(I've relaunched 4 times)

Note that even more strangely, if I do a re-scan, the extra Helm-VST lines disappear.

Hope that makes more sense for you than it does for me!

**Comment by rncbc** [comment]
no it doesn't make much sense to me either :(
but i do suspect very seriously that recent Helm VST is severely ill-behaved
i've tested some early first versions before, a year ago or so, but seemed ok at the time.
i guess i'll have to look at this sometime again
you're help is highly valuable though
cheers

**Comment by rncbc** [comment]
just to let us put on same page, I've compiled and installed helm-vst from [latest git](https://github.com/mtytel/helm.git) and have to confess that I fail to reproduce your findings--it all seems to work, no CPU overload, no duplicate inventory lines, no nothing strange happening (opensuse tumbleweed x86_64, kernel 4.14.7-rt7 here, if that matters).
seeya
