### ISSUE TITLE
A fresh Qtractor doesn't look for /usr/lib/lxvst

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qtractor#110]
A fresh install doesn't do so but only look in /usr/lib/vst . One can go to View->Options->Plugins and add the /usr/lib/lxvst path. And then, Qtractor will look into it, but no more in /usr/lib/vst which can be confusing for a end-used when rescanning.

A suggestion would be for Qtractor to use the 2 environment PATH variables: LXVST_PATH and VST_PATH as a default which the distro and/or sys-admin is supposed to fit with what's relevant. In my case, I've:
```
LXVST_PATH=/usr/local/lib/lxvst:/usr/lib/lxvst:/home/my_user/.lxvst
VST_PATH=/home/my_user/.vst:/usr/lib/vst:/usr/local/lib/vst

```
This could removes non-user-friendly ambiguities with PATH and get them straight to make music.

HTH

**Comment by sub26nico** [comment]
+1. Same here.

**Comment by rncbc** [comment]
mind you, the default search paths for Linux VSTs are the following, from first to last: 
```
   ~/.vst
   /usr/local/lib/vst
   /usr/lib/vst 
```
If you ever set at least one search path on the View > Options... > Plugins > Paths, the whole listing will override the default setting, no matter if it's been sourced from the VST_PATH environment variable or hard-coded as in the above.

as of today's commit (https://github.com/rncbc/qtractor/commits/2fa5c539) LXVST_PATH environment variable now takes precedence over VST_PATH as Linux-native VST plug-ins search path.

cheers && thanks

**Comment by trebmuh** [comment]
Good eyes about the order, thanks.

And thanks also for the commit, I'll test that asap and will report back.
