### ISSUE TITLE
MMC feedback not working when using MMC device

### ISSUE THREAD

**Issue by simonvanderveldt** [rncbc/qtractor#117]
When triggering a track or global action with an MMC Controller (MIDI device) there is no feedback being sent to the controller. Feedback is only sent when the action is triggered within Qtractor itself for example by clicking in the UI. This means there's no feedback loop to the controller so the controller cannot correctly show Qtractor's state.

This seems to be caused because `qtractorMainForm::midiMmcNotify` which is used to handle incoming MMC messages calls `qtractorMainForm::setTrack` which then calls `pTrack->set<action>(bOn)`. None of these includes any MMC feedback.
Compared to pressing a button, which is handled by `qtractorTrackStateCommand::redo` which calls `pTrack->set<action>(bOn)` directly but also includes code to [send feedback to an MMC controller](https://github.com/rncbc/qtractor/blob/master/src/qtractorTrackCommand.cpp#L949).

Any idea how this could/should be fixed?

**Comment by rncbc** [comment]
it is my understanding:

1. MMC "feedback" is only sent when the action is an initiative within qtractor: a corresponding MMC command is sent to the device;

2. when the initiative is on the controller device side then no "feedback" is issued from qtractor in reponse.

byee

**Comment by rncbc** [comment]
issue closed as "working as designed".

**Comment by simonvanderveldt** [comment]
@rncbc sorry, I haven't had time to respond yet, mainly because it takes some time to figure out the details.

MMC might be working as designed within Qtractor but it is missing what's called "closed loop" MMC which would be nice to have. Now I have no way to keep my hardware in sync with the state of Qtractor. Can we reopen this as feature request?

See below picture from the MIDI spec
![image](https://user-images.githubusercontent.com/204286/35049146-5c5c42ee-fb9f-11e7-80bb-726c8602e629.png)

**Comment by rncbc** [comment]
ok.

**Comment by simonvanderveldt** [comment]
> though no pormises ;)

No problem ;)
I'll see if I can get it working myself (somewhere in the next weekends)

**Comment by rncbc** [comment]
to let you know, mmc has been there from day one:
http://www.rncbc.org/drupal/node/15
(the kid inthe picture was 6, he's now 16:)
byee
