### ISSUE TITLE
Track movement improvement

### ISSUE THREAD

**Issue by schnitzeltony** [rncbc/qtractor#125]
Hi

have been busy setting up hardware and am still [1] but fun moments increase: Jam around. Doing so there is a thing that - ehh is not that - lets say - could be improved and maybe there is some time where there are some spare cycles left for (watch out here comes  yet another wishlist):

* add keyboard shortcuts for all track movements e.g Ctrl (or Alt have no idea what others do here) + Arrow Up for moving track up.
* if no clip is selected in it: why not delete current track by pressing 'Del'?
* guess this is more effort: How about moving track up and down by drag 'n drop (if there is something planned about selecting multiple tracks - I'd prefer 'Shift)?

[1] https://drive.google.com/drive/folders/1VUMqcRO8WxWpwMKYy06WZPZcSgrokq0h?usp=sharing

**Comment by rncbc** [comment]
hi,

i think most of those if not all are already there:

>-  add keyboard shortcuts for all track movements e.g Ctrl (or Alt have no idea what others do here) + Arrow Up for moving track up.

probably not for arrow keys but possible to have shortcuts assigned to either of Track/Move/Top, Up, Down, Bottom menu commands (see Help/Shortcuts...);

>-  if no clip is selected in it: why not delete current track by pressing 'Del'?

there's Shift+Del as default shortcut for Track/Remove Track menu command (current track);

>- How about moving track up and down by drag 'n drop (if there is something planned about selecting multiple tracks - I'd prefer 'Shift)?

you can do that already by start click-dragging over the 1st column of the track list (left panel); and yes extended multiple track selection is already there too, only that it applies to the 2nd and other columns and mostly serve to apply Shift or Ctrl over Mute and/or Solo over multiple, alternate and/or disjoint track sub-groups set up with Shift or Ctrl with click-dragging for lasso selection, etc.

hth.
cheers

**Comment by schnitzeltony** [comment]
Thanks - perfect!

**Comment by rncbc** [comment]
> So would you accept a hard-coded default?

nope :)

all the cursor/arrow keys have already their own hard-coded procedures while on the main track view and piano-roll etc.; as said those are not suitable to be mapped as pc-keyboard shortcuts, sorry.

byee
