### ISSUE TITLE
MIDI CC 7 creates texts in statusbar

### ISSUE THREAD

**Issue by schnitzeltony** [rncbc/qtractor#129]
Hi,

All the keyboards I use have a volume control. As soon as I do a move on this controller, qtractor displays this in the left part of the statusbar. Other controllers e.g Pitch-Bend don't show the events.

Problems (at least on weak machines):
* When I do a quick slide, the events take 2-3 seconds to be performed. It takes about this time to stop the statusbar 'spamming'.
* It seems that this statusbar display 'eats' a significant part of CPU cycles: I saw 5-10%. Moving other controllers not displayed in statusbar don't show additional processor load.

Is this a bug or a feature? If feature: Can I disable it somewhere?

**Comment by rncbc** [comment]
do you have a screenshot for evidence? what exactly does it show in the leftpart of the status bar?
i'm puzzled as bad, unless you've made some MIDI controller shortcut on something (some menu command) perhaps?

seeya

**Comment by schnitzeltony** [comment]
Hi Rui,

The text is generated in case you have a session with track that has same channel as the messages - see qtractorMainForm::midiCtlNotify (and the text is displayed in Message log too - I did not see that yet). The contents are:

> 21:54:25.943 MIDI CTL: Controller, Channel 1, Param 7, Value 71 (track 0, gain 0.559055)
21:54:25.970 MIDI CTL: Controller, Channel 1, Param 7, Value 69 (track 0, gain 0.543307)
21:54:25.978 MIDI CTL: Controller, Channel 1, Param 7, Value 72 (track 0, gain 0.566929)
21:54:26.115 MIDI CTL: Controller, Channel 1, Param 7, Value 77 (track 0, gain 0.606299)
21:54:26.124 MIDI CTL: Controller, Channel 1, Param 7, Value 74 (track 0, gain 0.582677)
21:54:26.134 MIDI CTL: Controller, Channel 1, Param 7, Value 69 (track 0, gain 0.543307)
21:54:26.139 MIDI CTL: Controller, Channel 1, Param 7, Value 74 (track 0, gain 0.582677)
21:54:26.166 MIDI CTL: Controller, Channel 1, Param 7, Value 76 (track 0, gain 0.598425)
21:54:26.186 MIDI CTL: Controller, Channel 1, Param 7, Value 75 (track 0, gain 0.590551)
21:54:26.206 MIDI CTL: Controller, Channel 1, Param 7, Value 74 (track 0, gain 0.582677)
21:54:26.219 MIDI CTL: Controller, Channel 1, Param 7, Value 73 (track 0, gain 0.574803)


I see the following options to go:
1. Remove appendMessages in qtractorMainForm::midiCtlNotify completely
2. Remove appendMessages in qtractorMainForm::midiCtlNotify for release-builds (my preference)
3. Add an option to show these messages only if the option is enabled

What do you prefer (some other way)? If you want I could create a patch (OK - 3. would take a bit longer).

For now I'll create a patch for 2. and add it to my embedded-build because this is an issue that causes additional XRUNS.

**Comment by rncbc** [comment]
go ahead with 2. https://github.com/schnitzeltony/qtractor/commit/49f2624 looks good.

**Comment by schnitzeltony** [comment]
Complete new experience: I could use master volume as effect now :)
