### ISSUE TITLE
Feature request: Auto crossfade/crossfade tool

### ISSUE THREAD

**Issue by alandmoore** [rncbc/qtractor#13]
One of my pain-points with qtractor is working with cross-fading clips that overlap.  If I have two clips that overlap (say, from a punch-in), and I want to smoothly crossfade between them, here's what I have to do:

- Slide the later clip's start-point out of the way, so I can work with the first clip
- Adjust the fade-out on the first clip
- Slide the second clip back to overlap with the first, and then set it's fade-in

Repeating this process over and over to find the right crossfade point is frustrating, because the fade-in curve on the second clip gets wiped out every time I slide it out of the way.

Suggestions to improve this:

- An "auto crossfade" feature that will automatically create a crossfade two overlapping clips
- Or, a "one-click" crossfade feature, that will create a crossfade between two selected clips
- Ideally, some kind of tool to adjust the overlap, cut-point, and fade curves of two clips without having to fuss individually with it.

Thanks for your consideration!

**Comment by rncbc** [comment]
have you seen this?
   http://www.rncbc.org/drupal/comment/6919#comment-6919

re. 1) What's the best way to select the edge of a clip when it overlaps 
with another one?

starting from [Feb 3]'s git head master (qtractor v0.7.4.1+) you can do 
all the things you asked there plus a brand new one: introducing the 
long overdue Clip/Cross Fade menu command! ;)

please test && tell.
cheers
-- 
rncbc aka. Rui Nuno Capela

**Comment by alandmoore** [comment]
I had not seen that.  I'm quite eager to try it out, very exciting!

Thank you

**Comment by alandmoore** [comment]
Just compiled the latest; crossfade works well, I'll have to try it in a heavy editing session, but I think this more than meets the need for now.  Thanks, this is great work!
