### ISSUE TITLE
Lost note-on/offs when placing a MIDI SEND before a synth plugin

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#133]
- Create a MIDI track
- Insert a synth plugin, e.g. Dexed or Linuxsampler and configure it
- Connect your MIDI keyboard and click on the track so you can play notes
- Place an MIDI INSERT before the synth plugin, don't connect SEND or RETURN
- Play some notes

In less than a minute I get hanging notes and strange effects like playing notes when I release(!) a key.

**Comment by rncbc** [comment]
please confirmed: only happens in a while the MIDI Insert pseudo-plugin is activated--when deactivated it doesn't seem to occur.

**Comment by rncbc** [comment]
please check it out from 0d06eae, test && tell

**Comment by suedwestlicht** [comment]
You fixed it. Thank you.
