### ISSUE TITLE
audio clips not always in sync when "jumping"

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#138]
Recent Qtractor from git, song with MIDI and audio tracks loaded
(Qtractor does this for a long time yet)

1. Place the song pointer on a position
2. Press SPACE to start playing
3. Press SPACE to stop playing
4. Place the song pointer back
5. Press SPACE to start playing
-> Everything is fine

1. Place the song pointer on a position
2. Press SPACE to start playing
3. Don't press SPACE to stop playing
4. Place the song pointer back while Qtractor is playing
-> Some audio clips are played early, not only some milliseconds but totally out of sync, even with small jackd buffer sizes. Stopping/starting Qtractor cures the problem.

It seems that placing the song pointer (I use middle click) while Qtractor is playing doesn't do the same thing (loading audio buffers?) as stopping the song, placing the song pointer and starting it.

**Comment by suedwestlicht** [comment]
Additional experience:

When an audio clip is out of sync pressing SPACE twice to stop/start playing doesn't help.
Placing the song pointer (middle mouse click) is needed, too.

**Comment by rncbc** [comment]
difficult to reproduce here; not one single evidence was detected yet.

**Comment by suedwestlicht** [comment]
I'll try to create a sample session where it can be reproduced easily.

**Comment by suedwestlicht** [comment]
Can't reproduce anymore.
