### ISSUE TITLE
Feature request: export/import settings of a single track or bus

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#141]
It would be cool if I could export all settings for a track or bus including plugin list and their settings and import it into another session.

At the moment I do it by copypasting <track>...</track> blocks.

**Comment by rncbc** [comment]
i'd take this as to export/import of a single plugin-list configuration and only; be that of a track or bus, no matter what:  it just doesn't make sense much to me to save it as a track or bus, as interchangeable entities alone, outside their session's context, but that might be just me short-seeing something... #)

**Comment by suedwestlicht** [comment]
Yep. Cool.

**Comment by rncbc** [comment]
implemented in https://github.com/rncbc/qtractor/commit/87a0f8

check plugin-list context-menu new entries: Import, Export...

cheers

**Comment by suedwestlicht** [comment]
Import/export works basically. Tested with MIDI track and audio bus. The plugins are in place after importing, but not their settings.

The saved export files looks good, though.

So I guess there is a bug in the importing function.

[exports.zip](https://github.com/rncbc/qtractor/files/3145261/exports.zip)

**Comment by rncbc** [comment]
maybe fixed in https://github.com/rncbc/qtractor/commit/54d3f2

thanks

**Comment by suedwestlicht** [comment]
Yes. Works fine. Thank you.
