### ISSUE TITLE
Display error: midi notes are displayed outside of the clips

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#152]
Latest Qtractor from Git:
Today I edited a song and it happened that the notes (grid) of some clips are displayed outside of the clip. Opening the clip in the MIDI editor and changing a note fixes it immedieately on the screen but it can happen again when loading the song. See screenshot.
![midi](https://user-images.githubusercontent.com/5550538/40282875-da8eba20-5c75-11e8-8b3a-9f77fdfc8450.jpg)

Using older Qtractor versions and loading the song shows the display bug, too. So I guess it happens when writing the qtr/qtz file.

**Comment by suedwestlicht** [comment]
Problem solved. Those affected clips where linked to clips on other tracks. While I was editing I deleted some tracks as well.

Unlinking the clips and linking to clips only on the same track solved the display problem.

**Comment by rncbc** [comment]
aha. maybe not linked to other tracks but rather on same MIDI channel and output bus, perhaps.

good catch.
cheers

**Comment by suedwestlicht** [comment]
Yes, indeed, linked to a clip on
- another track
- with the same MIDI channel
- and the same output bus

**Comment by rncbc** [comment]
can this issue be closed?
