### ISSUE TITLE
wrong vestige aeffectx.h effGetParameterProperties number

### ISSUE THREAD

**Issue by swesterfeld** [rncbc/qtractor#153]
qtractors aeffectx.h currently contains

```
const int effGetParameterProperties = 47; // missing
const int effGetVendorString = 47;
```

Now this looks wrong, they cannot both be 47. I believe the correct number for effGetParameterProperties should be 56, see also ardours aeffectx.h:

https://github.com/Ardour/ardour/blob/master/libs/ardour/ardour/vestige/aeffectx.h

**Comment by rncbc** [comment]
well, the ardour's version has its issues also but (eg. VstMidiEvent.deltaSamples vs. deltaFrames) but here fixed now by https://github.com/rncbc/qtractor/commit/f4cbc9301d8d782d61fbc1482355718137f833b6 .
thanks
