### ISSUE TITLE
It's not possible to desactivate the support of VST

### ISSUE THREAD

**Issue by ycollet** [rncbc/qtractor#16]
I compile qtractor from master branch on fedora 23 64 bits.
It's not possible to desactivate the VST support.
I added the following flags to configure:  --disable-vst --disable-vestige
I have the following sum-up:
  X11 Unique/Single instance . . . . . . . . . . . .: no
  VeSTige header support . . . . . . . . . . . . . .: no
  Gradient eye-candy . . . . . . . . . . . . . . . .: yes
  Debugger stack-trace (gdb) . . . . . . . . . . . .: yes

But when I compile qtractor:

d src/ && ( test -e Makefile.qtractor_vst_scan || /usr/lib64/qt5/bin/qmake /home/collette/repositories/qtractor/src/qtractor_vst_scan.pro -o Makefile.qtractor_vst_scan ) && make -f Makefile.qtractor_vst_scan 
make[2]: Entering directory '/home/collette/repositories/qtractor/src'
g++ -c -pipe -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o qtractor_vst_scan.o qtractor_vst_scan.cpp
qtractor_vst_scan.cpp:37:22: erreur fatale: aeffectx.h : Aucun fichier ou dossier de ce type
compilation terminée.

**Comment by rncbc** [comment]
nice catch. i guess it pays to runover the bleeding edge after all :)

yes, you're doing it from current git head. iow. glue still wet, hasn't dried off yet :)

anyway, thanks for the heads up.
cheers

**Comment by ycollet** [comment]
No problem :)
I am aware of the risks.

YC

**Comment by rncbc** [comment]
- fixed FTBFS when configure --disable-vst. (qtractor v0.7.5.6+)
https://github.com/rncbc/qtractor/commit/228a6ef
https://github.com/rncbc/qtractor/commit/c619dbe
