### ISSUE TITLE
Make qt5 default on a combined qt4/qt5 system

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#162]
On a qt4-System I added the qt5 libraries.

`./configure && make` creates a Qtractor linked against qt4.
To get a Qtractor linked against qt5 I have to use `./configure --disable-qt4 && make`

**Comment by rncbc** [comment]
not sure about this... qt4 support is being deprecated and will drop altogether by this years end.

you may try installing qtchooser and set QT_SELECT=5 before calling ./configure if you insist having both qt5 and qt4 development environments installed on your debian/ubuntu based system.

hth.
cheers

**Comment by suedwestlicht** [comment]
Since qt4-support will be dropped anyway soon you may close this issue.
