### ISSUE TITLE
Qtractor in Arch

### ISSUE THREAD

**Issue by JtLively** [rncbc/qtractor#167]
Opening Qtractor in Arch gives me the errors below and QJackctl doesn't start when I press "Start". 
What am I doing wrong ? 

could not open driver .so '/usr/lib/jack/jack_firewire.so': libffado.so.2: cannot open shared object file: No such file or directory 
 
JACK compiled with System V SHM support. 
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory) 
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory) 
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory) 
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory) 
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory) 
attempt to connect to server failed 
09:18:20.633 The audio/MIDI engine could not be started. Make sure the JACK audio server (jackd) and/or the ALSA Sequencer kernel module (snd-seq-midi) are up and running and then restart the session. 
lilv_world_add_plugin(): warning: Duplicate plugin <http://lv2plug.in/plugins/eg-metro> 
lilv_world_add_plugin(): warning: ... found in file:///usr/lib64/lv2/eg-metro.lv2/ 
_And does the same 2 lines above with dozens more plugins_

**Comment by rncbc** [comment]
JACK is not working on you and that is your major problem; not a Qtractor one to start width;

Make sure you setup and start JACK successfully from within QjackCtl first; only when fixed you may start Qtractor alright (or any other JACK client application for that matter).

OTOH. Arch seems to symlink "/usr/lib" -> "/usr/lib64" so that giving duplicate LV2 plugin warning messages on lilv_world_add_plugin(); to get rid of that set you own LV2_PATH environment variable to "~/.lv2:/usr/local/lib/lv2:/usr/lib/lv2" explicitly.

hth.

**Comment by JtLively** [comment]
Okay. Should I continue giving the QJackCtl errors here or on other repo Issues section?

[TIME] JACK was stopped
[TIME] JACK has crashed.
[TIME] Could not connect to JACK server as client. - Overall operation failed. - Unable to connect to server. Please check the messages window for more info.
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

**Comment by rncbc** [comment]
ALL message lines that follow "JACK server is starting..." and "JACK was stopped." are IMPORTANT to  what's possibly going wrong with your case (jack not working in your system).

please refer to your distro (arch linux?) community for help and support; at least check first the arch-wiki on the subject: https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit#Troubleshooting

hth.
