### ISSUE TITLE
qtractor_plugin_scan wrong installation place (or manpage missing)

### ISSUE THREAD

**Issue by alexmyczko** [rncbc/qtractor#168]
https://lintian.debian.org/maintainer/debian-multimedia@lists.debian.org.html#qtractor

If the binary /usr/bin/qtractor_plugin_scan is not to be called by the user, it would make
sense to /usr/lib/qtractor/qtractor_plugin_scan

otherwise, a manual page should be written for it.

**Comment by rncbc** [comment]
sorry. qtractor_plugin_scan is indeed of use to qtractor only but it also have to be located at the same file-system location.

fell free to make up a PR to a man page stating that it isn't for human consumption anyhow :)

cheers && thanks

**Comment by alexmyczko** [comment]
if it is not for human consumption do not put it in human $PATH. i will see if i can make a pr for ../lib/binary

**Comment by alexmyczko** [comment]
the man page is just wrong here.

the reason why i didn't PR it, i know it's hardcoded it'd be fine for debian/ubuntu. but I would prefer a proper fix by you, putting there the directory using the build system.

**Comment by rncbc** [comment]
if yout think it's fine to for debian than feel free to make it like so;
only that it's not going to make it upstream. sorry.

**Comment by rncbc** [comment]
hopefully fixed upstream (https://github.com/rncbc/qtractor/commit/e3083509)

thanks
