### ISSUE TITLE
Easy access to automation lines

### ISSUE THREAD

**Issue by thebutant** [rncbc/qtractor#171]
There's no beautiful way to put this: I tried Ableton.
Not because I really wanted to test it, but it was work and I had to for a night. One night only.
It was ok, though. And interesting to try anyway.

There was one thing I instantly liked, which I now humbly try to present as a feature request:
When pressing a plugin's parameter, this parameter automatically comes up in the automation line.
I'm pressing the frequency knob in a filter, and this frequency's automation line comes up.
This was actually rather time saving, especially when using automation that plays towards eachother (like frequency and resonance in a low pass filter), and changing back and forth is handy. I never realized how much time I spend pushing "A", scrolling the menu and finding the right parameter to automate.

My ideal solution would nevertheless not be the one of Ableton, as this changes automation lines even when you don't want to. But being able to push a button (let's say Alt) and press the knob whose automation line I'd like to get up - that would be a great feature.

**Comment by rncbc** [comment]
on qtractor,  on the plugin properties dialog (aka. generic stock GUI) you just right-click on the desired slider and voilá, there's this "Automation" on the context-menu...

hth.

**Comment by thebutant** [comment]
Ah, that's actually a lot of help.
Not the most intuitive, to be honest, but now that I know it - I'll sure use it.
Thanks!

Yes, I had a hunch that it couldn't be done in the plugins' GUIs, as they have their own small hotkeys where doubleclicking sometimes does this, sometimes it does something else, the same with rightclicking and ctrl and everything.

Properties, however, will be used a lot more often now. :)
