### ISSUE TITLE
2 missing translations

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qtractor#172]
I spotted 2 missing translations ("Presets" and "Direct Access") here:

![trad-manquantes](https://user-images.githubusercontent.com/8705846/46259967-98330900-c4e0-11e8-92f4-6acaa7ddb66c.png)

This second one is translated in the [French translation file](https://github.com/rncbc/qtractor/blob/master/src/translations/qtractor_fr.ts), the first one isn't there.

**Comment by rncbc** [comment]
fixed on https://github.com/rncbc/qtractor/commit/6fdd4650

thanks
