### ISSUE TITLE
calf-fluidsynth 0.9.1 not working with qtractor 0.9.3

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#184]
At first, loading the lv2 plugin was causing qtractor to puke. I fixed that by recompiling as suggested in #181 

However, attempts to load an sf2 within calf-fluidsynth are now failing. I know my plugin is working as expected when used via Ardour so it's hard to suspect it. [Here's a screenshot of that scenario](https://i.imgur.com/x3yI0Xo.png)

And now, [here's what the plugin looks like](https://i.imgur.com/YGCUVQE.png) after I fire it up from within qtractor and load the same sf2 file. Notice how patches are not assigned to channels 1-16. 

Can anyone duplicate this?

**Comment by rncbc** [comment]
not reproducible here while using calf-fluidsynth v0.90.0.76git.fb479a (current git head master in  https://github.com/calf-studio-gear/calf). also using libfluidsynth v2.0.2 fwiw.

byee.

**Comment by windowsrefund** [comment]
OK, that's encouraging. I'll check my version of libfluidsynth. Thank you.

**Comment by windowsrefund** [comment]
Wow, I'm using an old package on Ubuntu 18.10. This makes me sad.
`
ii  libfluidsynth-dev:amd64                       1.1.11-1                               amd64        Real-time MIDI software synthesizer (development files)
ii  libfluidsynth1:amd64                          1.1.11-1                               amd64        Real-time MIDI software synthesizer (runtime library)`

And now to figure out how to best upgrade.... closing this.
