### ISSUE TITLE
Feature request: Reverse clip

### ISSUE THREAD

**Issue by thebutant** [rncbc/qtractor#197]
A feature I'd find really neat, would be the possibility to right click a clip, have the option to press "reverse", and voila - the clip would play backwards.

Not very seldom I export clips from qtractor, open them in Audacity, reverse them, export, import to qtractor again. Being able to do this in qtractor - well, that would be lovely.

Any chance?

**Comment by rncbc** [comment]
not likely, sorry.

**Comment by oldcastlehq** [comment]
This "simple" feature is very handy when we use audio files like loops (hi hats) to make transitions in EDM music. I would ask you to kindly reconsider this FR.

Thank you!

**Comment by rncbc** [comment]
it is far from "simple" in implementation terms... 
if you think otherwise, and have a good plan on what to code it through, please make it a PR ;)
thanks

**Comment by oldcastlehq** [comment]
I have no idea how "simple" or difficult it is. But I will trust your judgement :-)
