### ISSUE TITLE
Some curve files are created newly at every save with inc'd numbers

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#198]
I prefer saving my sessions as qtr because I share soundfonts between projects and store some additionall files in the song's directory.

Since I rsync the song's directory between several computers I see the files that are changed or added.

I noticed that some curve files are overwritten and other curve files are newly created with an incremented number:
- Start Qtractor
- Load a song
- Mute/unmute first track to force activation of the "save" button
- Save qtr
- rsync

```
hm@wolke:~/qtractor/die_ferne$ ./putsong.sh 
sending incremental file list
aktuell/
aktuell/die_ferne-Drums_high_AudioAuxSend_419ddb5e_curve-102.mid
aktuell/die_ferne-Drums_low_AudioAuxSend_419ddb5d_curve-102.mid
aktuell/die_ferne-Pauke_high_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne-Pauke_low_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne-Perc_1_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne-Perc_2_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne-V_m1_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne.qtr
```

- Close Qtractor
- Start Qtractor
- Load previous song
- Mute/unmute first track to force activation of the "save" button
- Save qtr
- rsync

```
hm@wolke:~/qtractor/die_ferne$ ./putsong.sh 
sending incremental file list
aktuell/
aktuell/die_ferne-Drums_high_AudioAuxSend_419ddb5e_curve-103.mid
aktuell/die_ferne-Drums_low_AudioAuxSend_419ddb5d_curve-103.mid
aktuell/die_ferne-Pauke_high_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne-Pauke_low_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne-Perc_1_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne-Perc_2_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne-V_m1_AudioAuxSend_419ddb5c_curve-1.mid
aktuell/die_ferne.qtr
```
As you see some files are overwriten (as it should be), like
die_ferne-V_m1_AudioAuxSend_419ddb5c_curve-1.mid

Other files are newly created with incremented number, like
die_ferne-Drums_high_AudioAuxSend_419ddb5e_curve-103.mid

So I get an ever growing number of some curve files.

Is this a bug?

**Comment by suedwestlicht** [comment]
I use the most recent Qtractor from gtit head.

**Comment by rncbc** [comment]
question might rather be: are the number of files growing or just the number of the suffix?

in certain cases, the suffix numbers are indeed version numbers and specifically for curve files (ie. automation data) the must not ever be shared across sessions; they are supposed to be unique (no matter whether the suffix gets increased on each save (the previous one should be auto-deleted if not in use).

this is working as is for quite some time--it is not a bug on the latest release i'm afraid: it is like so. probably since TYOQA :)

**Comment by suedwestlicht** [comment]
When die_ferne-Drums_low_AudioAuxSend_419ddb5d_curve-130.mid is created then die_ferne-Drums_low_AudioAuxSend_419ddb5d_curve-129.mid is retained, so I have 130 of those now.

**Comment by rncbc** [comment]
ok. does it happen only on that one? if yes what characteristic, specific to that track and aux-send insert, do you find relevant there? is it because you have more than one aux-send in the same track and automation is enabled on either of those?

**Comment by rncbc** [comment]
maybe you can find this https://github.com/rncbc/qtractor/commit/c5a11c9e one notch up in better behavior  :)

cheers

**Comment by suedwestlicht** [comment]
It's fixed :) Thx
