### ISSUE TITLE
Feature request: offline calculation of pitch/speed

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#200]
Pitch/speed changes of audio clips are calculated in realtime and use a noticable amount of realtime CPU that may lead to xruns when used on several tracks.

Proposal: Changing pitch/speed of an audio clip generates a working copy that can be played as-is, with already calculated pitch and speed.

Of course that can be achieved manually by creating the audio files as appropriate and importing them. But it would be very convenient if Qtractor would do that by itself.

**Comment by rncbc** [comment]
you can do that for ages: just select and Clip > Merge...

**Comment by suedwestlicht** [comment]
Wow! Thanks and sorry.

**Comment by phbrt** [comment]
so this is closed?

**Comment by suedwestlicht** [comment]
Yes. Thx.
