### ISSUE TITLE
Crash when loading some sessions after 9cb3586f592e402721e947af23fab8755da5cba0

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#203]
Hi Rui,

commit 9cb3586f592e402721e947af23fab8755da5cba0
Author: rncbc <rncbc@rncbc.org>
Date:   Thu Mar 14 18:44:36 2019 +0000

    - Plugin chain total latency is reset/re-calculated on playback start. (EXPERIMENTAL)

crashes Qtractor when I load some songs. I couldn't find out what dustiguishes the crashing sessions from non-crashing sessions. Maybe it's bus -> bus

**Comment by suedwestlicht** [comment]
A song with track -> bus -> bus  loads ok. Still can'tfind out what causes the crash. I added a stack trace.
[qtractor_dump.txt](https://github.com/rncbc/qtractor/files/2972454/qtractor_dump.txt)

**Comment by rncbc** [comment]
please hold your horses: the xpdc branch is in merge-flux and strange thing might happen :)

cheers+thanks

**Comment by suedwestlicht** [comment]
OK :) But JFTR: f3feb46d05df09e46f5d3420c5825dc8292d1e85 fixed it.

Thx.
