### ISSUE TITLE
x42 digital peak limiter's UI elements have no effect

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#204]
- http://x42-plugins.com/x42/x42-limiter
The knobs have no audible effect, e.g. "input gain"

When I load Carla (as lv2) into Qtractor and load the limiter into Carla then everything works as exspected.

**Comment by rncbc** [comment]
confirmed but not sure this is a qtractor issue: the controls on the generic UI (plugin > Properties...) work just fine and they get feedback onto the custom GUI alright (plugin > Edit).

**Comment by suedwestlicht** [comment]
Since it doesn't happen when Carla is used as "middelware" I though I'd start here. If you think it's not a Qtractor issued I'll file a report with x42,

**Comment by rncbc** [comment]
as a matter of fact, it is a bug in qtractor after all: the LV2 UI Touch interface implementation was flawed, now fixed in https://github.com/rncbc/qtractor/commit/de6955f5ac0a7309f965f89c96370f25d5bc7c19.

sorry && thanks

**Comment by suedwestlicht** [comment]
The bug with x42 autotune is fixed, too. Probably the same cause. Now you can click on the piano keys to mark "forbidden" notes in x42 autotune.

Thx.
