### ISSUE TITLE
Crash when toggling "omni" at the end of the song

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#206]
- Load a song with MIDI tracks
- Go to the end of the song
- Toggle the "omni" checkbox and click "OK"
-> Qtractor crashes, sometimes only when toggle to "on"

Qtractor doesn't crash when at the beginning of the song.

It looks as if Qtractor wants to reposition the song cursor and segfaults.

**Comment by rncbc** [comment]
maybe something else... something related in (yours) MIDI track in particular when editing the main Track/Properties... dialog? 

just can't reproduce this crash. so a crash gdb back-trace would be helpful here. thanks

**Comment by suedwestlicht** [comment]
Hmm... it's not that easy to reproduce as I thought. I had those crashed on another machine, too, but not in every song. So it might be related to that special song's routing.
