### ISSUE TITLE
Bug: Mark and move splits track

### ISSUE THREAD

**Issue by thebutant** [rncbc/qtractor#210]
Hey.
It turns out I have a habit I never thought of:
When moving tracks (especially long ones), I often hold down shift, mark a part of the tracks, then click them with left mouse button to mark the rest. Before moving.
But now this splits the tracks where I first marked them. Even though the whole track is marked when moved, it splits where it was initially marked before I clicked left mouse button to mark the rest. But only when shift or ctrl are pressed, it seems. Was this possible to understand?
Everything seems fine until the track is moved, then part of the track stands unmoved, and I've gotten a split.
I hope this is an easy one to fix.

Best regards and easter greetings

**Comment by rncbc** [comment]
what you with "mark a part of the tracks" ? is that *selecting* a part of a clip ?

tracks don't get split, clips do.

shift+left-clicking on a clip often selects the whole clip, adding it to the current selection of clips in session; left-click+dragging the selection will split/cut the clip(s) at the selection margins, iif these are not at the precise left and/or right clip edges; thus, a whole selected clip won't ever get split or cut away when moving the selection.

this is not quite a bug or misbehavior, or so--it looks as working as ever was, as designed :)
cheers

**Comment by thebutant** [comment]
Yea, sorry. By "marking a track" I actually meant selecting a clip. 8)

However, you write a sentence that makes me think what I'm reporting is not intentional: "A whole selected clip won't ever get split or cut away when moving the selection." 'Cause that's exactly what's happening (in Qtractor 0.9.6 from KXStudio repos, now tested on several computers). I'll try to explain more precisely:

1/ Select some part of a clip, not the whole thing.
2/ Press down shift or ctrl and left-click the clip to select the rest of it, so the whole clip is now selected.
3/ Drag the clip to move it.
4/ For me the clip now splits where it was selected in step no 1, even though the whole clip was selected when moved. It behaves as if only the area from step no 1 was selected.

If this is intentional, then the intentions are pretty new, 'cause Qtractor didn't behave like this just a short time ago.

Did this make more sense? Is it possible for you to reproduce?

**Comment by rncbc** [comment]
yes now it is clear and it is also here reproduced; it really happens if you only use shift (or ctrl) when clicking to select the whole clip (2) and then try to drag-move it afterwards (3)---yes, it is a bug and probably a more than a decade old one :)

it will try to fix it soon... meanwhile please don't use shift nor ctrl to the select the "rest" of the clip (as in 2), just click on it will do ;)

cheers

**Comment by rncbc** [comment]
maybe fixed now on https://github.com/rncbc/qtractor/commit/ad660e1

thanks

**Comment by thebutant** [comment]
Great - thanks! :D
Well, it might seem like an unnecessary thing to do, the way I described it in my little recipe.
But when doing for example sound design, where there are lots of short clips here and then a couple of 40 minutes long clips going out to the right, and everything should be moved without loosing sync - then it's really a quite handy thing to do.
So I'm truly grateful that you fixed it.

Wish you a good weekend!
