### ISSUE TITLE
Solved: Gsinth vst kill qtractor when closing its UI 

### ISSUE THREAD

**Issue by RarogCmex** [rncbc/qtractor#217]
Gentoo Linux x64, qtractor 0.9.8 own build
Steps to reproduce
1. Create new midi track in Qtractor
2. Add Gsinth plugin from here https://www.gvst.co.uk/portpage.htm
3. Open Gsinth interface, change any parameter
4. Close Gsinth interface. Qtractor falls down

**Comment by rncbc** [comment]
Well, i fail to reproduce the crash, no matter how many times I try to load, change and close the GSinth (.so dated May 2, 2015 from GVSTLinux64Beta.zip).

Of course I do my own build though it's on an up to date openSUSE Tumbleweed x86_64, kernel 5.2, Qt 5.13.0; genuine VSTSDK 2.4.

cheers

**Comment by RarogCmex** [comment]
That's very strange. When I rebuild qtractor with Debug flags, I can't reproduce issue: all works stable. But with Release build It falls down again. How can I get you debug data?
Yes, I use vestige headers. 
Of course debug data provide nothing interesting
qtractorPluginFactory::createPlugin(0x5591adaaa060, "/usr/lib64/vst/GSinth.so", 0, 3)
qtractorVstPlugin_HostCallback(0x0, audioMasterVersion(1), 0, 0, 0x0, 0)
qtractorVstPlugin_HostCallback(0x5591b0e55d60, audioMasterGetSampleRate(16), 0, 0, 0x0, 0)
qtractorVstPlugin_HostCallback(0x5591b0e55d60, audioMasterGetVendorString(32), 0, 0, 0x7ffdb393dc00, 0)
qtractorVstPlugin_HostCallback(0x5591b0e55d60, audioMasterGetProductString(33), 0, 0, 0x7ffdb393dc00, 0)
qtractorVstPluginType[0x5591ae77d650]::open() filename="/usr/lib64/vst/GSinth.so" index=0
qtractorVstPlugin[0x7fd18400e040] filename="/usr/lib64/vst/GSinth.so" index=0 typeHint=3
qtractorVstPlugin[0x7fd18400e040]::setChannels(2) instances=1
qtractorVstPlugin[0x7fd18400e040]::releaseConfigs()
qtractorVstPlugin[0x7fd18400e040]::openEditor(0x0)
qtractorVstPlugin[0x7fd18400e040]::closeEditor()
qtractorVstPlugin[0x7fd18400e040]::openEditor(0x0)
qtractorVstPlugin_HostCallback(0x5591b0e55d60, audioMasterGetVendorString(32), 0, 0, 0x7fd145184940, 0)
qtractorVstPlugin_HostCallback(0x5591b0e55d60, audioMasterGetProductString(33), 0, 0, 0x7fd145184940, 0)
qtractorVstPlugin[0x7fd18400e040]::closeEditor()

**Comment by RarogCmex** [comment]
gdb without debug simbols: 
 (gdb) c
Continuing.
[Thread 0x7fcb1b536700 (LWP 24887) exited]

Thread 1 "qtractor" received signal SIGSEGV, Segmentation fault.
0x00007fcb5ee8e54b in QWindow::destroy() () from /usr/lib64/libQt5Gui.so.5
(gdb) 

_____
I think I must build it with -0g or something like

**Comment by rncbc** [comment]
all my own testing have been carried out with both release and debug builds. no difference.

cheers

**Comment by RarogCmex** [comment]
OK, seems much helpful. Any idea how to continue improving debug information?
(gdb) c
Continuing.
[New Thread 0x7fd36790d700 (LWP 5729)]
[Thread 0x7fd36790d700 (LWP 5729) exited]

Thread 1 "qtractor" received signal SIGSEGV, Segmentation fault.
0x00007fd3afb94d60 in QWindow::isTopLevel() const () from /usr/lib64/libQt5Gui.so.5
(gdb) c
Continuing.
[Thread 0x7fd3a458b700 (LWP 5601) exited]
[Thread 0x7fd384bf7700 (LWP 5636) exited]

**Thread 17 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fd365309700 (LWP 5641)]
qtractorMidiInputRpn::process (this=this@entry=0x7fd365308bf0, ev=0x0) at qtractorMidiEngine.cpp:304
304     qtractorMidiEngine.cpp: Нет такого файла или каталога.**
(gdb) c
Continuing.

Thread 3 "QDBusConnection" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fd39bb63700 (LWP 5602)]
0x00007fd3af0e7fa3 in write () from /lib64/libc.so.6

**Comment by rncbc** [comment]
there's weird stuff in there to start with: re. Thread 3 "QDBusConnection" received signal SIGPIPE, Broken pipe.

wtf! qtractor does not make use of QDBusConnection whatsoever. It must be something on your whole Qt build somehow.

byee

**Comment by RarogCmex** [comment]
That's not strange because it's termination stage of qt. My latest trying of continue gdb is not error I think. Sorry, I'm not very experienced in debugging.
```
(gdb) c
Continuing.

Thread 3 "QDBusConnection" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fd39bb63700 (LWP 5602)]
0x00007fd3af0e7fa3 in write () from /lib64/libc.so.6
```

**Comment by RarogCmex** [comment]
[core.10425.tar.gz](https://github.com/rncbc/qtractor/files/3387141/core.10425.tar.gz)
That's coredump of error.  Please tell me If I must install any additional debug simbols or something.

**Comment by rncbc** [comment]
please can you try on a new build from git master as of https://github.com/rncbc/qtractor/commit/1ffd2ee0 ?

thanks

**Comment by RarogCmex** [comment]
Ok, I has just performed successful tests. The issue seems solved.
Thank you, Rui.
