### ISSUE TITLE
Wishlist: UI improvement: protect direct access

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#219]
If many plugins are loaded in a track's or bus' plugin box then there appears a little scrollbar. I can scroll with the mouse wheel even if the mouse pointer is over a plugin slot - but only if the plugin has no "direct access" parm set. If it's set then the parm changes.

That can happen accidentally.

It would be helpful if a "direct access" parm could only be changed with the mouse wheel if the plugin was activated by a mouse click.

I

**Comment by rncbc** [comment]
i wonder if this is


> It would be helpful if a "direct access" parm could only be changed with the mouse wheel if the plugin was activated by a mouse click.

the mouse-wheel is supposed to work without any clicking though, let alone the same mouse-wheel often serves as (middle)-button, at least on most if not all mouses I've seen to date.

you can however get rid of the direct-access changing by wheel: just remove or comment out https://github.com/rncbc/qtractor/blob/b8c3852f73979d84e4e704c6085ef1e1acfc7cd5/src/qtractorPluginListView.cpp#L1432 .

cheers

**Comment by suedwestlicht** [comment]
Thanks. This patch protects me from changing direct access parms unintentionally.

[protectdaparms.txt](https://github.com/rncbc/qtractor/files/3428130/protectdaparms.txt)
