### ISSUE TITLE
Qtractor for win mac

### ISSUE THREAD

**Issue by Reaper10** [rncbc/qtractor#22]
Qtractor for win mac

**Comment by rncbc** [comment]
this is o non-issue.

qtractor is a linux excluisive application, and it will stay that way under my watch :)

sorry.

**Comment by Reaper10** [comment]
am I the only one that wants this

**Comment by rncbc** [comment]
nope. it surely has been asked before. for instance if you look at to the sf.net/projects/qtractor site you'll see that years ago someone rated one lousy star just because there's no windoze version  :)

cheers

**Comment by Reaper10** [comment]
sorry I want to try audition can't afford it your program is  just as good please think about after all more people see your awesome software the more people can help you

**Comment by Reaper10** [comment]
you still not doing mac/win

**Comment by rncbc** [comment]
there are no plans beyond the horizon either
