### ISSUE TITLE
Weird window behaviour

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#221]
I use devilspie to move Qtractors main window to virtual desk 1 and its mixer window to virtual desk 2.

Since a few commits the mixer window can't be moved to another desk manually (menu greyed out) or jumps to the desk with the main window (devilspie).

The behaviour on the same desk is weird, too. Clicking to the main window's button on the taskbar shows the mixer window. I have to click on the mixer window's button twice to show the main window.

**Comment by rncbc** [comment]
sorry for the inconvenience

you can check whether commenting out these lines has any effect on your case: https://github.com/rncbc/qtractor/blob/5bd2e84bb161158b91590ce1b1da8f37be64cfbf/src/qtractorMidiClip.cpp#L1116-L1118

cheers

**Comment by suedwestlicht** [comment]
Thx. You fixed it with commit 651d526bccf0bd29d05ca3b732b52dd2da40db94
