### ISSUE TITLE
Increase Vst buffers for receiving names

### ISSUE THREAD

**Issue by jpcima** [rncbc/qtractor#226]
Hi. To receive program names of Vst, Qtractor is using a buffer of 24 bytes.
By the plugin specification, this is sufficient, but it isn't in practice.

Since the space is so short, some plugins will fill up to a larger amount, and hosts will usually prepare a larger buffer to protect against these cases.

Among others, Surge is identified to have trouble with Qtractor. https://github.com/surge-synthesizer/surge/issues/545
Surge fills up to 63 for program names.

It may be advisable to set a buffer of 256 for safety, and it can recommandable also to do the same for others that apply. (parameters, name, vendor, etc.)

See also https://github.com/surge-synthesizer/surge/pull/1153

**Comment by rncbc** [comment]
fact was, qtractor uses 32 bytes for `effGetEffectName` and 64 bytes for `effGetVendorString` and `effGetProductString`... past tense 'coz now they're all 256 bytes (https://github.com/rncbc/qtractor/commit/bbc2f14c).
hope it's enough:)
thanks

**Comment by jpcima** [comment]
I think, you missed this one. It's the one of particular interest among all of them. :wink:
Regarding the problem I have at hand, at least. (regarding the current developer version of surge, it is now also fixed at the plugin side.)

https://github.com/rncbc/qtractor/blob/bbc2f14cb2060a253145e3decc5b4f174e68987d/src/qtractorVstPlugin.cpp#L1015

**Comment by rncbc** [comment]
thanks again. https://github.com/rncbc/qtractor/commit/457d405

let me know if there's'more :)

**Comment by jpcima** [comment]
I'm going to be annoying and nitpick one more time. :)
The commit 457d405 removes the `memset` call.

By doing so, it's trusting the plugin implementer to terminate the buffer with null.
It's better not to trust programmers to make this correct.

For instance, see this fragment of code of surge before the latest fix.
```
       strncpy(text, s->storage.getPatch().name.c_str(), 63);
```
If the patch name is exactly of the size limit 63, strncpy does not terminate the buffer.

As indicated from `strncpy(3)`
>Warning: If there is no null byte among the first n bytes of src, the string placed in dest will not be null-terminated.

**Comment by rncbc** [comment]
ok  https://github.com/rncbc/qtractor/commit/e082548c should make it right now.

thanks twice again.

**Comment by jpcima** [comment]
It's looking good thanks. :+1:
