### ISSUE TITLE
Feature request: add an instrument track

### ISSUE THREAD

**Issue by ycollet** [rncbc/qtractor#24]
Like with ardour: add an instrument track.
A track which take as input MIDI events and produce real audio.
It's an hybrid between qtractor audio track and qtractor midi track.
The problem with the midi track is that if the plugin doesn't react to the MIDI messages send by the MIDI mixer strip, then the volume is not controled.
With the instrument mixer strip, the plugin will produce audio and the mixer strip will control directly the audio output of the plugin and not via midi messages.

**Comment by rncbc** [comment]
indeed, in qtractor MIDI tracks are the equivalent of instrument tracks on other DAWs; the audio output is rendered to an audio ouput bus of your choice (default is Master); the audio volume/pan controls are therefore situated on the output bus and not on the MIDI track; MIDI track volume/pan controls do indeed send channel MIDI CC#7 and CC#10 respectively and its the responsibility of the MIDI plugin(s) there inserted whether recognize and/or implement the way it should according to the GM standard.

having a brand new instrument track type is just redundant and thus overruled. sorry.

**Comment by ycollet** [comment]
And what about adding a button to MIDI rack to allow to directly control the volume and not sending MIDI CC ?
There are many plugin synth which doesn't answer to Midi CC ...

----- Mail original -----
De: "Rui Nuno Capela" <notifications@github.com>
À: "rncbc/qtractor" <qtractor@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 13 Juin 2016 22:54:17
Objet: Re: [rncbc/qtractor] Feature request: add an instrument track (#24)



indeed, in qtractor MIDI tracks are the equivalent of instrument tracks on other DAWs; the audio output is rendered to an audio ouput bus of your choice (default is Master); the audio volume/pan controls are therefore situated on the output bus and not on the MIDI track; MIDI track volume/pan controls do indeed send channel MIDI CC#7 and CC#10 respectively and its the responsibility of the MIDI plugin(s) there inserted whether recognize and/or implement the way it should according to the GM standard. 

having a brand new instrument track type is just redundant and thus overruled. sorry.

**Comment by rncbc** [comment]
On 2016-06-14 07:35, ycollet wrote:
> And what about adding a button to MIDI rack to allow to directly
> control the volume and not sending MIDI CC ?
>  There are many plugin synth which doesn't answer to Midi CC ...
> 

there's something in the plans, like introducing a plugin-chain 
separator as a movable pseudo-plugin insert, representing the fader 
controls (volume/pan) allowing for pre-fader plugin inserts (the current 
standing) as well as post-fader plugin-inserts.

it is on this pseudo-plugin separator that a new control might be 
introduced, specially for MIDI tracks, where one may select which type 
of fader control and meter display are shown, MIDI or audio.

cheers
-- 
rncbc aka. Rui Nuno Capela

**Comment by ycollet** [comment]
OK, with a volume plugin and a panning plugin which react to MIDI CC ...
I will try to find such plugins.

----- Mail original -----
De: "Rui Nuno Capela" <notifications@github.com>
À: "rncbc/qtractor" <qtractor@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 14 Juin 2016 10:21:42
Objet: Re: [rncbc/qtractor] Feature request: add an instrument track (#24)

On 2016-06-14 07:35, ycollet wrote: 
> And what about adding a button to MIDI rack to allow to directly 
> control the volume and not sending MIDI CC ? 
> There are many plugin synth which doesn't answer to Midi CC ... 
> 

there's something in the plans, like introducing a plugin-chain 
separator as a movable pseudo-plugin insert, representing the fader 
controls (volume/pan) allowing for pre-fader plugin inserts (the current 
standing) as well as post-fader plugin-inserts. 

it is on this pseudo-plugin separator that a new control might be 
introduced, specially for MIDI tracks, where one may select which type 
of fader control and meter display are shown, MIDI or audio. 

cheers 
-- 
rncbc aka. Rui Nuno Capela

**Comment by ycollet** [comment]
Do you have some reference about volume and pan plugins compatible with MIDI CC ?

**Comment by rncbc** [comment]
On 06/16/2016 10:13 AM, ycollet wrote:
> Do you have some reference about volume and pan plugins compatible with
> MIDI CC ?
>

i'm pretty sure the vee-one-suite do :)

yoshimi and probably zynaddsubfx do as well.

all fluidsynth based plugins should (but not sure).

iow, any plugin that complies to the GM standard.

byee
-- 
rncbc aka. Rui Nuno Capela

**Comment by ycollet** [comment]
I was just asking for amplifier plugin a panoramic plugin.
I wanted to add these plugins with a plugin which doesn't support MIDI CC so as to be able to control the volume and the pan of this plugin via and amp and pan plugin.

**Comment by ycollet** [comment]
I created a lv2 plugin that does volume and panning using MIDI CC:

https://github.com/ycollet/vopa

There are 2 versions: one mono version which does volume only and the stereo version which does volume and panning.

Tested with NoiseMaker and master version of qtractor ...

**Comment by rghvdberg** [comment]
this is exactly what is need 
 
>I created a lv2 plugin that does volume and panning using MIDI CC:
>
>https://github.com/ycollet/vopa
>
>There are 2 versions: one mono version which does volume only and the stereo version which >does volume and panning.
>
>Tested with NoiseMaker and master version of qtractor ...
