### ISSUE TITLE
[Feature Request] Select controller when punch in

### ISSUE THREAD

**Issue by XaviP** [rncbc/qtractor#241]
Hi Rui, thanks for this useful piece of software.

I'm playing in qtractor 0.9.9 with sounds of [Virtual Playing Orchestra](http://virtualplaying.com), specifically with the Performance Orchestra sfz scripts:

> The Performance Orchestra uses the MOD wheel to control volume. Key velocity (how fast you hit a key on your MIDI controller) selects the articulation (sustain, staccato etc) while still slightly affecting the volume.

As sfz files are charged in Carla (sforzando plugin), I can play giving expression with the mod wheel. So, Qtractor saves perfectly the controller(1) Modulation Wheel, and I can edit the curves of this controller. Strings and brass sound quiet realistic :-)

A further step in this workflow would be the capacity of punching in only the mod wheel controller in a track or clip. This way one could re-write the expression in an already saved track or clip.

Currently, I can record another midi track with only mod wheel controller and export both tracks through a bus, to mix them. But when I'm recording this new track I can't listen to the mod wheel effect while playing.

Well, I don't know if this feature is really a need for more users, but I've wanted to contribute with my two cents. Thanks again.

**Comment by rncbc** [comment]
hi, you may already take one of the following two options:

1) you can record "overdub" directly on an existing MIDI clip: you may select the clip and hit menu Clip > Record or just open the MIDI clip editor and go menu File > Record.

2) you don't need to create a new track to record new MIDI material: you can record to a new clip that will overlap any previous one on the same track; when done you can merge the two or more clips into a single one, via Clip > Merge, which boils down to the same as you go as exporting and merging through an output bus (and then add the exported result file into the session).

hth.
cheers

**Comment by XaviP** [comment]
Waw! Clip layer system is very powerfull. Thanks again. Closing FR

**Comment by rncbc** [comment]
on a late note, always consider to upgrade to the latest and greatest... v0.9.9 is half-a-year-old already ;) 

cheers
