### ISSUE TITLE
 [Feature request] Change the order of events that happen at the same time

### ISSUE THREAD

**Issue by XaviP** [rncbc/qtractor#243]
Hi! Working in 0.9.11, with the MIDI clip editor like this:

![event](https://user-images.githubusercontent.com/6750293/71321054-5f4fcd00-24b4-11ea-99ca-e22f0cca8b2f.png)

When I want to add a new event (like Pgm Change) in a time that there are other events (here four Note On) the new event is always created in last place of that time. But the intention is that the program change occurs before notes on. The only way I've found to change the order of events in the same time is to move the notes in the piano roll, so the Pgm Change event takes first place in that time.

I don't know if there's already this feature hidden somewhere, but it would be very useful the ability to change the order (maybe in the contextual menu in the events window? or with a keyboard shortcut?)

Thanks!

Edit: btw I notice in last version, one can select any event in window event, without changing the dropdowns. This is very useful!!

**Comment by rncbc** [comment]
you can forget that!

qtractor does not support interleaved Pgm Change events, in fact they will get mercilessly ripped off 
as soon you save the session.

in qtractor model convention, all bank-select and program-change (PC) are fixed properties of a MIDI track/channel and they get issued at the beginning of timeline or playback if you changed MIDI device, output bus state or its connections.

otoh. interleaved PC events may however exist on a MIDI sequence alright but only if you load or import them from an "alien" MIDI file, that meaning a SMF file that was not produced by qtractor previously. in which case you only get the first BS+PC as track/channel setup, if any.

hth.
cheers

**Comment by XaviP** [comment]
Ok, thanks for explanation.
Then, two more things:

1.- The same applies to volume controler:
![volume](https://user-images.githubusercontent.com/6750293/71321858-0a19b880-24c0-11ea-9609-a4090347a805.png)

2. Where can I document all this as my contribution to the project? Here?
https://sourceforge.net/p/qtractor/wiki/Home/
Maybe as a "Howto edit MIDI clips"?
