### ISSUE TITLE
Horizontal zoom changes window position

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#244]
When horizontal zooming (ctrl + mousewheel) in the main window it scrolls to the top. I'd prefer it wouldn't change the vertical position.

**Comment by rncbc** [comment]
please check if it's fixed with https://github.com/rncbc/qtractor/commit/43d5d6c

cheers

**Comment by suedwestlicht** [comment]
Nearly. When I scroll down max, position the mouse pointer over one of the tracks in the lowest third then it's fixed. When I position the mouse pointer in the middle or top third then the window is still repositioned vertically.

**Comment by suedwestlicht** [comment]
Seems to be fixed with commit b88cf8719af3b57ba301edbcb737935d89686373

Thx Rui
