### ISSUE TITLE
wrong position of notes in MIDI editor when switching measure

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#245]
Seen with recent git head (and maybe much longer):

- create midi track in 4/4
- insert a 3/4 beat
- create a clip immediately after the 3/4 beat is over, so it's a 4/4
- insert a note at the beginning
- main view shows the note at the correct position
- MIDI editor shows the note too early
![wrongpos](https://user-images.githubusercontent.com/5550538/72685230-75b76b80-3ae8-11ea-89fa-f94cc0ab7183.jpg)

**Comment by rncbc** [comment]
looks like it's the drawing of the grid in MIDI clip editor that's is wrong... the event is in fact in the correct position.

note that, as you can see on your screenshot, bar 8 has the same visual length ws it were still on 3/4.
thanks

**Comment by suedwestlicht** [comment]
Yes, probably a grid display issue.

**Comment by rncbc** [comment]
maybe fixed by https://github.com/rncbc/qtractor/commit/7be95de
cheers

**Comment by suedwestlicht** [comment]
Yep. You fixed it. Thx.
