### ISSUE TITLE
Meters on midi track list too small

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#249]
![Bildschirmfoto_2020-03-13_19-14-29](https://user-images.githubusercontent.com/5550538/76648618-532d5600-655f-11ea-86d7-14201e2fd698.png)

Channel number is displayed above meters. Would look better if channel number was displayed right from the meters so the meters can use full track's height.

**Comment by rncbc** [comment]
mitigated with https://github.com/rncbc/qtractor/commit/f1568d0 ;)
cheers

**Comment by suedwestlicht** [comment]
That's a good solution. Thx.
