### ISSUE TITLE
Wishlist: CTRL+Mouse Wheel for changing plugins' Direct Access parms

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#257]
When there are several plugins in a plugin box then the box's content gets scollable with a tine scrollbar. If I don't hit it exactly I change accidentally Direct Access parms.

How about using the mouse wheel for scrolling the box but CTRL+mouse wheel to change Direct Access parms?

**Comment by rncbc** [comment]
implemented in https://github.com/rncbc/qtractor/commit/4fc19a9f

**Comment by suedwestlicht** [comment]
Great! Thx Rui.
