### ISSUE TITLE
Make snd-seq-midi instructions more verbose

### ISSUE THREAD

**Issue by probonopd** [rncbc/qtractor#261]
Running qtractor-0.9.12-52.x86_64.AppImage on Xubuntu 18.04 live ISO, I am getting

> The audio/MIDI engine could not be started. Make sure the JACK audio server (jackd) and/or the ALSA Sequencer kernel module (snd-seq-midi) are up and running and then restart the session

I did

```
sudo modprobe snd-seq-midi
```

and then restarted Qtractor, this did not resolve the issue for me.

it would be nice if the dialog box would be a bit more verbose, telling me _exactly_ what to do.

**Comment by rncbc** [comment]
what about the jack server? was it started, up and running?

**Comment by probonopd** [comment]
No. I don't use JACK. I read the "and/or" in the error message such that either JACK __or__ ALSA are needed, am I misreading it?

**Comment by rncbc** [comment]
both are needed: 1) jack-server sure needs to be up and running; 2) the alsa-seq kernel module has to be loaded (it usually is on system boot).

but ok, fair enough I reckon it's an English language nitpicking issue ;)

cheers
