### ISSUE TITLE
drumkv1 inside Qtractor: cannot enter values in input fields with keyboard

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#263]
recent Qtractor and drumkv1 from git:

I can't enter any values in drumkv1's input fields with my keyboard, e.g. preset name.

As a standalone jack version it works ok. As lv2 loaded in Carla, too.

**Comment by rncbc** [comment]
what Qt5 version is that? it should works fine on Qt >= 5.14; previous versions would indeed have the bug.

**Comment by suedwestlicht** [comment]
About Qt: "This program uses Qt version 5.5.1."

Platform is Xubuntu 16.04 LTS

**Comment by rncbc** [comment]
I'd suggest you to try with adding this https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.14.2-xenial, the very same that it's being used for travis-ci.org (cf. `.travis.yml` for details).

**Comment by suedwestlicht** [comment]
Unfortuantey it's broken.

qt514-meta-full has an error where the doc package wants to overwrite the same file that's in another package. Trying to remove the doc package fails because of dependencies.

qt514-meta-minimal doesnt't seem to be enough: "Project ERROR: Unknown module(s) in QT: x11extras"

So I might use the workaround copy&paste with mouse into textfields if neccessary until I update my computers from 16.04 to something beyond 18.04, since 18.04 comes with Qt 5.9.5.

**Comment by rncbc** [comment]
you only need to install **qt514base**, **qt514tools** and possibly **qt514x11extras**; 
then `source /opt/qt514/bin/qt514-env.sh`and configure build as usual.

**Comment by suedwestlicht** [comment]
Thx Rui.

I compiled both Qtractor and drumkv1.

Qtractor: "This program uses Qt version 5.14.2."
drumkv1 lv2 plugin: "This program uses Qt version 5.14.2."

The bug ist still there. I can't enter values or delete contents in text or number fields with the keyboard.

**Comment by suedwestlicht** [comment]
drumkv1-lv2 loaded in carla-lv2 loaded in Qtractor works ok.

But drumkv1-lv2 loaded in Qtractor not.

**Comment by suedwestlicht** [comment]
I investigated further.  It's not Qtractor. It's drumkv1. An old drumkv1 from 2019-07-18 works ok.

**Comment by suedwestlicht** [comment]
OK, one last statement fpr drumkv1:

- commit b83834e842a7abb44595c61f056f5820bfe0dc1c breaks it
"Yet again, got rid of LV2UI::Qt5 as an option"

- commit 377e7b33ec167d4000b0258cf659dbdd7427e44c is OK

**Comment by suedwestlicht** [comment]
I opened issue #32 for drumkv1.

**Comment by rncbc** [comment]
as from 64da210 you can now test both ways (libsuil vs. native) provided you have opted on View > Options... > Plugin > Editor > Select plugin's editor (GUI) if more than one are available.

try it out and tall it makes any difference
cheers

**Comment by suedwestlicht** [comment]
Qtractor with libsuil, drumkv1 as-is without changing ttl file:
- X11 Gui: can't enter data with keaboard in fields
- X11 (native) Gui: can't enter
- external: enter data works

BUT: the selection window does not appear reliably after loading a qtr file and trying to open drumkv1's Gui. Mostly I simply can't find it.

So I'll stick with patching drumkv1's ttl file at the moment.

**Comment by rncbc** [comment]
> BUT: the selection window does not appear reliably after loading a qtr file and trying to open drumkv1's Gui. Mostly I simply can't find it.

note that the answer to "don't ask this again" option is saved into session file (.qtr) and taken into account when you open it later

**Comment by suedwestlicht** [comment]
Sorry for my poor description. When the selection didn't open I hadn't checked "don't ask this again", so drumkv1's Gui didn't open at all because I couldn't select a Gui.

**Comment by suedwestlicht** [comment]
The issue happens with Qt6 as well, even on a recent Debian Bookworm.
Compiling drumkv1 with -DCONFIG_LV2_UI_X11=no -DCONFIG_LV2_UI_EXTERNAL=yes showed no GUI at all.
To make a long story short:
Removing the X11 part in drumkv1_ui.ttl helped.
Now the correct working UI of drumkv1 in Qtractor is chosen by default.

**Comment by suedwestlicht** [comment]
Works for me.
