### ISSUE TITLE
BSD support

### ISSUE THREAD

**Issue by oldcastlehq** [rncbc/qtractor#268]
Does qtractor work on BSD system? If not, any plan to support them?

**Comment by rncbc** [comment]
qtractor is tied to ALSA, so, unless BSD supports ALSA, there are no plans to port it away from GNU/Linux.
byee

**Comment by userabc123xyz** [comment]
> unless BSD supports ALSA, there are no plans to port it away from GNU/Linux.
as far as I know, BSDs use ALSA for sound in many cases. To what extend do they have to use it in order to be able to run Qtractor?
