### ISSUE TITLE
Standard GUI's parm faders don't work

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#269]
Sliding does nothing.

![1](https://user-images.githubusercontent.com/5550538/83786483-060add00-a693-11ea-8fa2-2cda6db83705.png)
![2](https://user-images.githubusercontent.com/5550538/83786494-0905cd80-a693-11ea-98ea-7d2a25aa8bed.png)

**Comment by rncbc** [comment]
and the spin-box?

**Comment by suedwestlicht** [comment]
The numerical field? It works but doesn't affect the slider.

**Comment by rncbc** [comment]
all the time and on any session, plugin or situation? 
is that a GUI thing, meaning that any change of value doesn't have any effect on sound?
(all that to say that it fails to reproduce here)
byee

**Comment by suedwestlicht** [comment]
It's when loading an existent session.

1.) new session
2.) create audio track
3.) load LADSPA stereo amp

-> slider works

4.) save sessioin
5.) load session

-> slider doesn't work. Moving it has no effect on the numerical field and no effect on th volume.

[amptest.qtr.zip](https://github.com/rncbc/qtractor/files/4734550/amptest.qtr.zip)

**Comment by rncbc** [comment]
got that and probably fixed in https://github.com/rncbc/qtractor/commit/6b1abe76

thanks

**Comment by suedwestlicht** [comment]
Yes, it's fixed. Thx.
