### ISSUE TITLE
VST3 and VST paths issues

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qtractor#270]
Hi Rui.

Following our talks on IRC #lad, I've been investigating a bit more about why it takes ~12 minutes on my computer to make a VST3 scan. Note that I have 2 VST3 plugins: _Surge_ and _sfizz_ in `/usr/lib/vst3/`, and 226 VST2 plugins in `/usr/lib/vst.`Here my findings when launching a VST3 scan:

In `.config/rncbc.org/Qtractor.conf`:
- if `Vst3Paths=/usr/lib/vst3` and `VstPaths=@Invalid()`, then my 2 VST3 are found super quickly (~1 second)
- if `Vst3Paths=/usr/lib/vst3` and `VstPaths=/usr/lib/vst`, then it takes ~12 minutes to scan and it doesn't find my 2 VST3 plugins

Now, look at this weirdy half-baked hybrid one:
- if `Vst3Paths=@Invalid()` and `VstPaths=/usr/lib/vst, /usr/lib/vst3` then it takes ~12 minutes to scan and it finds my 2 VST3 plugins

All of that with a build from master 03aaf92.
I hope you will make sense of that.

**Comment by rncbc** [comment]
good catch. maybe fixed in https://github.com/rncbc/qtractor/commit/e1a1d6ba

thanks

**Comment by trebmuh** [comment]
Rebuild from master head (6b1abe7) and it now works perfectly and quickly.
Thanks Rui.
