### ISSUE TITLE
Crash with beat slicer / beat repeater

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qtractor#271]
I can load [those plugins](https://github.com/blablack/beatslash-lv2) in Qtractor 0.9.14, but when I activate them, then Qtractor crashes.

@jpcima advise me to ask here for executing the GUI in a separate process maybe. I'm not sure what that means (not a programming person here), but maybe that rings a bell for you.

**Comment by rncbc** [comment]
AFAIK those plugins are designed for Ingen; they expose CV ports, something that won't get any love from qtractor any time soon.

sorry.

**Comment by trebmuh** [comment]
That makes sense. Alternatively, would there is a way for Qtractor not to crash then? Even a plugins blacklist in `~/.config/rncbc.org/Qtractor.conf`would be fine in the worst case scenario.

**Comment by rncbc** [comment]
there's no current way to blacklist any plugins in qtractor

cheers

**Comment by trebmuh** [comment]
Closing now, see #272
