### ISSUE TITLE
Cannot save files added to Files pane

### ISSUE THREAD

**Issue by oldcastlehq** [rncbc/qtractor#273]
Maybe I'm doing something wrong or I didn't completly understand the Files concept. 
I'm would like to add all my samples (organised by folder) in the Files pane. But everytime I close the program, I lose all my files added there. I tried to create a template with all my samples added to Files pane, but it didn't save that information. Is that a bug?

Is there any easy/fast way to access my samples from inside qtractor?

**Comment by rncbc** [comment]
entries in the Files pane are saved in regular sessions, but not templates (which are supposed to have no content anyway).

you probably wish to take a look at the (View > Windows >) File System pane instead ;)

cheers

**Comment by oldcastlehq** [comment]
Oh my...great!

Thank you!
