### ISSUE TITLE
VST3 and audio in/out missing for certain synths

### ISSUE THREAD

**Issue by tank-trax** [rncbc/qtractor#274]
**qtractor version: 0.9.14.20git.6027dc**
Operating System: Debian GNU/Linux 10
Kernel Version: 4.19.0-9-rt-amd64
OS Type: 64-bit

Issue: Certain VST3i's are missing inputs/outputs

For example Surge has 2 inputs and 6 outputs and the VST3 in Qtractor only has 6 outputs 

I've tested the VST3 using Bitwig, Reaper and Carla and Surge VST3 does have 2 inputs and 6 outputs available using those hosts

Surge VST2 also has the 2 in and 6 out in **qtractor** 

![Screenshot_20200623_225226](https://user-images.githubusercontent.com/41337033/85493284-9b1f3880-b5a4-11ea-860f-e599fb48162a.png)
![Screenshot_20200623_225241](https://user-images.githubusercontent.com/41337033/85493288-9ce8fc00-b5a4-11ea-82a1-b5920f2ebfb3.png)

I've managed to build OB-Xd as a VST3 using JUCE6 and surprisingly it works, also in Bitwig, Reaper and Carla. However in Qtractor for the VST3 there is no audio. 

OB-Xd also has the 2 out for the VST2

![Screenshot_20200623_225127](https://user-images.githubusercontent.com/41337033/85493394-d3bf1200-b5a4-11ea-8933-b84a43346adf.png)
![Screenshot_20200623_225149](https://user-images.githubusercontent.com/41337033/85493399-d4f03f00-b5a4-11ea-84b5-407581688e63.png)

**Comment by rncbc** [comment]
the lack of audio inputs on Surge.vst3 is known as qtractor does not support side-chaining scenarios; though the plugin works and should render audio outputs as normal (at least through its first two ports).

however, the case for no audio ouputs on OB-Xd.vst3 is a mistery at the moment; we'll need to investigate a little bit deeper and most certainly need to have access to OB-Xd.vst3 source code for a debug build; can you provide that here? much appreciated.

**Comment by tank-trax** [comment]
I just thought I'd let you know that this is now resolved. OB-XD VST3 now has audio.
