### ISSUE TITLE
"Fixed potential crash on changing audio output" breaks LADSPA amp plugin

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#275]
With
```
commit 06781f37fc0f8509a132c372150196e9b7043be7
Author: rncbc <rncbc@rncbc.org>
Date:   Thu Sep 24 18:37:24 2020 +0100

    - Fixed potential crash on changing audio output buses channel count. (EXPERIMENTAL)
```
the LADSPA amp plugin /usr/lib/ladspa/amp.so (amp_stereo, package ladspa-sdk) doesn't work anymore. It outputs always at full volume.

**Comment by rncbc** [comment]
hi, can you please elaborate the steps to reproduce the behavior?

tested with /usr/lib/ladspa/amp.so (Stereo Amplifier) on a MIDI track, inserted after an instrument plugin, changed the audio output bus from stereo and mono and back, and the gain takes effect as it should as expected on either way (it would crash before, if changing from stereo to mono output bus. 

are you sure the plugin is activated (i know you know this very well, that little fake-LED is lit green...) ?

cheers

**Comment by suedwestlicht** [comment]
Stupid me! Sorry fpr the inconvenience. It's not the amp that makes the distorted and loud sound. It's the AUX send that gets rchanged to (none).

1.) Start Qtractor
2.) Create MIDI track
3.) Create audio bus 
4) Add an AUX send to the MIDI track to the audio bus.
5.) Save session (qtr)
6.) Quit Qtractor
7.) Start Qtractor
8.) Load the saved session

Now the AUX send doesn't go to the audio bus anymore but to (none).

**Comment by rncbc** [comment]
gotcha.

should be fixed now on https://github.com/rncbc/qtractor/commit/5289686

thanks

**Comment by suedwestlicht** [comment]
Confirmed. Thx.
