### ISSUE TITLE
Monitor button of audio tracks doesn't work as expected

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#290]
0.) Start Qtractor
1.) Create audio track
2.) Create input audio bus
3.) Connect a jack input with a microphone (or other sound source) to the audio bus
4.) Use the input audio bus as input for the audio track

Regardless if the "monitor"-button of the audio track is active or not, the signal is always fed to the audio track's output bus.

**Comment by rncbc** [comment]
maybe Track > Auto Monitor is on and the track is current?

**Comment by suedwestlicht** [comment]
Uuh, yes. Stupid me. Thx.

It would be helpful if the monitor LED is lit, too, when Auto Monitor is active and the track is current.
What do you think?
