### ISSUE TITLE
Stop previewing audio file in File System

### ISSUE THREAD

**Issue by oldcastlehq** [rncbc/qtractor#299]
A suggestion for improving  the UX a bit.

When I preview a file from the File System, there is no way to stop the preview. That's quite annoying. Two suggestions:

a) make use of space bar. So, I can use the space bar to play and stop the audio file.
b) add a play and stop button.

**Comment by rncbc** [comment]
yes there is one:  File System rclick/context-menu last item: Play (toggle).

**Comment by oldcastlehq** [comment]
Thanks.
