### ISSUE TITLE
"audio/MIDI engine could not be started": ALSA library on FreeBSD doesn't support MIDI

### ISSUE THREAD

**Issue by yurivict** [rncbc/qtractor#301]
![image](https://user-images.githubusercontent.com/271906/113475139-9dae9880-9428-11eb-8084-3c0c3cd54717.png)

But Jack interface is fully capable to pass MIDI signals.
It should be possible to connect a piano through the HW MIDI interface and route its MIDI signals through JACK to qtractor, no?

**Comment by rncbc** [comment]
nope. qtractor takes the ALSA Sequencer driver as its main MIDI engine, and not JACK. It is actually stated on its manifest since day one.

**Comment by yurivict** [comment]
Is JACK less functional than ALSA when it comes to MIDI?

**Comment by rncbc** [comment]
no, when Qtractor was conceived there was no JACK-MIDI at all; OTOH. on GNU/Linux at least, JACK takes ALSA as the system's MIDI hardware/device interface for sure.

what you need there is that the ALSA-MIDI (aka. ALSA-sequencer) interface to be fully-implemented on freeBSD, which I think is not or else not set up and running properly (if is actually implemented).

**Comment by yurivict** [comment]
> what you need there is that the ALSA-MIDI (aka. ALSA-sequencer) interface to be fully-implemented on freeBSD, which I think is not or else not set up and running properly (if actually implemented).

ALSA library exists on FreeBSD, but it attempts to open ```/dev/snd/seq``` which does not exist because it is a Linux-only kernel device. FreeBSD uses OSS for audio including MIDI.

So I need to have an OSS-to-ALSA library or JACK-to-ALSA library to satisfy the qtractor's requirement to work through the ALSA interface.

Do you know if such libraries exist?

**Comment by rncbc** [comment]
none. sorry to tell

**Comment by hselasky** [comment]
FreeBSD now has audio/alsa-seq-server, which create /dev/snd/seq .

**Comment by yurivict** [comment]
@hselasky 

Thank you for this tip and for creating ```alsa-seq-server```. I just added the port for Qtractor: audio/qtractor.

https://cgit.freebsd.org/ports/commit/?id=285ba5106abdb1f50d858622cfae3b0de88407db
