### ISSUE TITLE
qtractor-0.7.8: FTBFS with Qt 5.7.0

### ISSUE THREAD

**Issue by tgurr** [rncbc/qtractor#31]
```
[...]
checking for qmake-qt5... /usr/bin/qmake-qt5
checking for qmake... /usr/x86_64-pc-linux-gnu/lib/qt5/bin/qmake
checking for Qt library version >= 5.1... no; Qt 5.1 or greater is required

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =media-sound/qtractor-0.7.8:0::media --destination installed --x-of-y 4 of 4:
  * When installing 'media-sound/qtractor-0.7.8:0::media':
  * When running an ebuild command on 'media-sound/qtractor-0.7.8:0::media':
  * Install failed for 'media-sound/qtractor-0.7.8:0::media' (paludis::ActionFailedError)
[...]
```

```
# qmake-qt5 --version
QMake version 3.0
Using Qt version 5.7.0 in /usr/x86_64-pc-linux-gnu/lib
```

I had to add
```
export CXXFLAGS="${CXXFLAGS} -std=c++11"
```
to our build script to allow qtractor-0.7.8 to successfully configure/compile with Qt 5.7.0.

**Comment by rncbc** [comment]
On 06/29/2016 03:21 PM, Timo Gurr wrote:
> |[...] checking for qmake-qt5... /usr/bin/qmake-qt5 checking for qmake...
> /usr/x86_64-pc-linux-gnu/lib/qt5/bin/qmake checking for Qt library
> version >= 5.1... no; Qt 5.1 or greater is required Error: * In program
> cave perform install --hooks --managed-output --output-exclusivity
> with-others =media-sound/qtractor-0.7.8:0::media --destination installed
> --x-of-y 4 of 4: * When installing
> 'media-sound/qtractor-0.7.8:0::media': * When running an ebuild command
> on 'media-sound/qtractor-0.7.8:0::media': * Install failed for
> 'media-sound/qtractor-0.7.8:0::media' (paludis::ActionFailedError) [...] |
>
> |# qmake-qt5 --version QMake version 3.0 Using Qt version 5.7.0 in
> /usr/x86_64-pc-linux-gnu/lib |
>
> I had to add
>
> |export CXXFLAGS="${CXXFLAGS} -std=c++11" |
>
> to our build script to allow qtractor-0.7.8 to successfully
> configure/compile with Qt 5.7.0.
>

that sounds great!

as a matter of fact, i'm still targeting qt5.6.1, though on g++6.1 
already, and the issue isn't raised on there.

i guess the addition of "--std=c++11" should be addressed to qt5.7 
upstream, inscribed on its own new qmakespec or sth.

none of of the current qtractor-0.7.8 c++ code demands for c++11 
standard. none. so it probable is a janitorial misalignment mess as 
usual (search order paths, headers, not on par to resp. shared libs and 
whatnot:))...

byee
-- 
rncbc aka. Rui Nuno Capela
