### ISSUE TITLE
Wishlist: vu meter on instrument tracks

### ISSUE THREAD

**Issue by rghvdberg** [rncbc/qtractor#33]
The midi "vu meter" don't represent the actual volume of the audio coming from the plugin. 
Would be a great help with mixing.

**Comment by rncbc** [comment]
On 07/20/2016 04:30 PM, rghvdberg wrote:
> The midi "vu meter" don't represent the actual volume of the audio
> coming from the plugin.
> Would be a great help with mixing.
>

that kind of "vu meter", or better said, technically speaking, a 
ppm(eter), for MIDI track instrument audio output, is nothing less than 
the audio output bus that is currently assigned as for mix-down.

yes, you can certainly have several MIDI track/instruments (audio 
render) to converge into the same audio output bus--on default, it's the 
first one available, the "Master" audio out, but you can switch to any 
other as long it's created or available properly--check the MIDI track 
plugins chain/list rclick/context-menu : Audio > (submenu) ...

remember that, on qtractor signal flow model, audio output buses are in 
fact primary mix-down devices then, secondarily are interfaces to the 
outer world ie. output ports.

hth.
byee
-- 
rncbc aka. Rui Nuno Capela

**Comment by rghvdberg** [comment]
Real life example.
Lots of instrument tracks. Project I'm working on now has 16+ tracks and
more will be added.
I listen to my mix. Somethings wrong. I suspect some clipping.
But which track?
Solution now is to solo each track and watch the master out bus. This can
be very tedious and time consuming.

Other option would be to make a bus for every instruments track...  Seems a
bit much.

I admit it could be that I have a very peculiar usage of Qtractor, working
only with instrument tracks.

Btw:I really love working with qtractor...

**Comment by rncbc** [comment]
On 07/20/2016 05:43 PM, rghvdberg wrote:
> Real life example.
> Lots of instrument tracks. Project I'm working on now has 16+ tracks and
> more will be added.
> I listen to my mix. Somethings wrong. I suspect some clipping.
> But which track?
> Solution now is to solo each track and watch the master out bus. This can
> be very tedious and time consuming.
>

as said, you aren't locked in to a one and only audio output (master) 
bus; you can have as many as you find suitable. and they don't have to 
be all stereo 2-channels either ;)

otoh. this whole subject has been addressed in this other issue:
   https://github.com/rncbc/qtractor/issues/24
which you already acknowledged. the monitoring that is being asked here 
--audio ppm for MIDI instrument tracks--is included on those mentioned 
plans for that "pseudo-plugin-separator" contraption whatever :)


> Other option would be to make a bus for every instruments track... Seems a
> bit much.

not that much, really. if you often use the same studio rig and take 
advantage of the "new session template" option.


>
> I admit it could be that I have a very peculiar usage of Qtractor, working
> only with instrument tracks.
>

completely ok. qtractor is a general purpose music production sequencer, 
so it might just fit , reasonably speaking, any peculiar work-flow... 
it's just isn't, won't ever be, a 
do-it-all-in-one-dang-walled-garden-place for sure.


> Btw:I really love working with qtractor...
>

thanks. i do love it too although that ain't news ;)

ttfn.
-- 
rncbc aka. Rui Nuno Capela

**Comment by rghvdberg** [comment]
Oh sorry, totally missed the ppm thing in #24
Let's close this!
