### ISSUE TITLE
qtractor does not play when using ZynReverb LV2 plugin

### ISSUE THREAD

**Issue by be1** [rncbc/qtractor#332]
I am upgrading from 0.9.19 to 0.9.26 and one of my sessions having both MIDI and audio tracks and LV2 plugins does not play (jack is up and the graph is connected). Sometimes it gives a loud and hard noise on session load. Sometimes It just doesn't play any sound while the vertical red bar runs. Another weird issue (that was already in 0.9.19): the message window can't stop saying: «Sending key 'state' to UI failed, out of space»

information:
$ qtractor --version
Qtractor 0.9.26
Qt: 5.15.3
$ jackd --version
jackdmp version 1.9.14 tmpdir /dev/shm protocol 8

If you need me to give you more info, feel free to ask.
If you need a zip file of my session directory, just ask me. I can upload it to my web server and give you a link.

**Comment by be1** [comment]
Okay, further info:
The LV2 plugin ZynReverb is causing the loud hard noise on session opening, and/or no sound on playback button press.
So... It may either be a ZynReverb issue, or an LV2 issue in Qtractor. Deactivating the plugin allows playback to run correctly.

**Comment by rncbc** [comment]
could it be a ZynReverb LV2 mishap between a old version, when it got saved originally, and the current loading one?

does it still play well if you run the session through an older qtractor v0.9.19 ?

**Comment by be1** [comment]
I discarded my old session with ZynReverb, replacing it with Calf Reverb.
When I use ZynReverb in a brand new test session, the problem occurs.
The LV2 ZynReverb is, from /usr/lib/lv2/ZynReverb.lv2/ZynReverb.ttl

    lv2:microVersion 0 ;
    lv2:minorVersion 8 .

I'll try to get an update of ZynAddSubFX stuff.

**Comment by be1** [comment]
Okay. It appears that the regression comes in **0.9.23**.

**Comment by rncbc** [comment]
maybe fixed in >= 0.9.26.7git.https://github.com/rncbc/qtractor/commit/a2922a

many thanks for your findings

**Comment by be1** [comment]
I installed 0.9.26.7git.https://github.com/rncbc/qtractor/commit/a2922a in /usr/local but it cannot find any LV2 plugin now.
Do I have to install it in /usr ?

**Comment by be1** [comment]
> maybe fixed in >= 0.9.26.7git.[a2922a](https://github.com/rncbc/qtractor/commit/a2922a)
> 
> please test && tell
> 
> many thanks for your findings

Yes it works fine ! Thanks for your quick fix.
