### ISSUE TITLE
Vertical zoom scrolls the clip editor to the right

### ISSUE THREAD

**Issue by maxigaz** [rncbc/qtractor#337]
To reproduce:

1. Open a new session and create a new MIDI track.
1. Place two edit markers (blue vertical lines) anywhere on the track.
1. Create a clip, open its piano roll editor, and place some notes.
1. Click on to View > Zoom > Vertical.
1. Move the mouse wheel while holding Ctrl.

After doing the above, the editor's view always scrolls to the right, so far that none of the clip's notes are visible anymore. It happens with both new and existing clips, except when the clip starts at 00:00:00.

OS: Arch Linux
Qtractor version: 0.9.26
Qt version: 6.3.0

**Comment by rncbc** [comment]
maybe you missed that when using the mouse zooming is centered on it's pointer location?

**Comment by maxigaz** [comment]
> maybe you missed that when using the mouse zooming is centered on it's pointer location?

No, I didn't. The behaviour is the same regardless of where the mouse pointer is.

**Comment by rncbc** [comment]
> The behaviour is the same regardless of where the mouse pointer is.

right, it was me that missed the 4. above (change zoom orientation to Vertical...)
now I see what you mean, and confirm the issue

will look into it soon
thanks

**Comment by rncbc** [comment]
should be fixed now in 465f7af7

cheers

**Comment by maxigaz** [comment]
I've just tried it (by installing `qtractor-git` from the AUR), and I can confirm that vertical zoom works. Thank you!

However, I noticed a regression: the problem is now present when zoom is set to either 'All' or 'Horizontal' in the menu. (This is the opposite of what occurs in Qtractor 0.9.26, where 'All' and 'Horizontal' work fine, and 'Vertical' has the bug.)

**Comment by rncbc** [comment]
probably now you have to refer to my first reply ;)

**Comment by maxigaz** [comment]
> probably now you have to refer to my first reply ;)

I don't understand why you're saying that. I'm here, doing my best to file a report _and_ help you with testing, and you're still acting like you don't believe me. Why?

By the way, I've just double checked, and I believe it's _you_ who should refer to _my_ reply:

> The behaviour is the same regardless of where the mouse pointer is.

Now, I appreciate the work you've done on Qtractor so far, and I'd be glad to report additional bugs (in case there are any), but if you're making comments like these, I'm not sure what to think, to be honest.

**Comment by rncbc** [comment]
please don't take it personal, thing is that now after the https://github.com/rncbc/qtractor/issues/337#issuecomment-1126771718, horizontal and all should work fine as intended, but always centered on the current mouse pointer location, that was the call onto "my first reply"; none of my comments are the least dismissive of your kind; if it sound like so or worse then please accept my apologies, that was not my intention, at all

nevertheless please check again which version build are you actually running: it should be no less than v0.9.26.21. note that the later is working just fine on all zoom directions on all tests that I've carried out.

**Comment by maxigaz** [comment]
I accept the apology and thank you for the explanation (which puts it into context and changes the whole meaning).

> please check again which version build are you actually running: it should be no less than v0.9.26.21

As I mentioned above, I was testing the AUR package [qtractor-git](https://aur.archlinux.org/packages/qtractor-git), which runs `git clone https://github.com/rncbc/qtractor.git` and compiles the source. This means that your very latest commit should already be included, so that I could test it.

As a matter of fact, I can also confirm this by running `pacman -Qi qtractor-git`. The output mentions this as the version number: `0.9.26.r21.g465f7af7-1`. And sure enough, 465f7af7 is the commit id you pushed yesterday.

> note that the later is working just fine on all zoom directions on all tests that I've carried out.

So, you can't reproduce it anymore? I'm out of ideas, then.

**Comment by rncbc** [comment]
> So, you can't reproduce it anymore? I'm out of ideas, then.

yes correct, i cannot reproduce it anymore: vertical zooming works right now as no more horizontal scrolling suddenly occurring on clips not starting on time 00:00:00; horizontal zooming also works now as intended, but note that it can seem to scroll _accidentally_ if the zooming center (ie. mouse pointer) is not far from the clip start location.

**Comment by maxigaz** [comment]
I've reinstalled Qtractor with your latest commit 0df4f62 and now I can also confirm that zoom works in all modes. Thank you very much!
