### ISSUE TITLE
Unable to enter exact value for automation points

### ISSUE THREAD

**Issue by maxigaz** [rncbc/qtractor#338]
When I double click on an automation point, a small text input appears for specifying its exact value. When I change this number and press Enter, nothing happens.

This happens in Qtractor 0.9.26.22git.0df4f6 under Arch Linux.

**Comment by rncbc** [comment]
fixed in >= 0.9.26.26git.[d63f74](https://github.com/rncbc/qtractor/commit/d63f74e7e)

thanks

**Comment by maxigaz** [comment]
Thank you!
