### ISSUE TITLE
Recording automation from plugins doesn't work when a parameter is controlled by MIDI CC

### ISSUE THREAD

**Issue by maxigaz** [rncbc/qtractor#339]
In Qtractor 0.9.26.26git.d63f74, I use the LV2 versions of Surge XT and Vitalium, both of which support the mapping between MIDI CC (for example, a fader or the modulation wheel) and an arbitrary parameter.

When I select the same parameter in the Automation options in Qtractor and turn on Record mode, the changes can be heard in real time, but Qtractor doesn't actually record any automation nodes. To make it work, I have to change the parameters in the plugins' window using the mouse.

I've done some online research, and from what I understand, it's not possible to map MIDI CC directly in Qtractor for automation tracks, so I thought that if a plugin supports MIDI CC Learn on its own, it can be a great workaround. However, I'm not sure why it works only when the mouse is used.

**Comment by rncbc** [comment]
maybe fixed in >= 0.9.26.27git.[2b5d43](https://github.com/rncbc/qtractor/commit/2b5d43b)

please test && tell

**Comment by maxigaz** [comment]
It's working now. Thank you very much!
