### ISSUE TITLE
Duplicating an armed track confuses the record button

### ISSUE THREAD

**Issue by alandmoore** [rncbc/qtractor#34]
Duplicating an audio track that is armed for recording seems to confuse the R button on the duplicated track.

Steps to reproduce:
1. Create an audio track
2. Arm it for recording
3. Duplicate the track
4. The duplicated track does not appear to be armed for recording, however, if you then begin recording a clip will be recorded on the ducplicated track.
5. If you click the arm button, it appears to light up but now the track is actually disarmed for recording.
6. To "unconfuse" the button you have to disarm again and re-arm.

Seeing this on 0.7.8 on Antergos with GNOME 3.20, though it may have been around before that.

**Comment by rncbc** [comment]
On 08/11/2016 09:19 PM, Alan D Moore wrote:
> Duplicating an audio track that is armed for recording seems to confuse
> the R button on the duplicated track.
>

mostly fixed on today's v0.7.8.8+
   https://github.com/rncbc/qtractor/commit/56ef6f8

thanks
-- 
rncbc aka. Rui Nuno Capela

**Comment by alandmoore** [comment]
I will check it out at the first opportunity.  Thank you!
