### ISSUE TITLE
MIDI track is muted when an effect plugin is removed

### ISSUE THREAD

**Issue by maxigaz** [rncbc/qtractor#341]
To reproduce:

1. Create a MIDI track, add an instrument plugin such as Surge XT to it.
1. Add an effect plugin to the same track, such as LSP Compressor Stereo. (This is now listed under Surge XT in the left side panel.)
1. Check that sound is working.
1. Remove LSP Compressor from the track.
1. There's no audio coming out of the track anymore.

I can make it work again only by saving and reloading the session or undoing the removal of the plugin.

This happens in Qtractor 0.9.26.27git.2b5d43 under Arch Linux.

**Comment by rncbc** [comment]
maybe fixed in cc249a2

thanks

**Comment by maxigaz** [comment]
It's working, indeed. Thank you!
