### ISSUE TITLE
Silders in various LV2 plugins jitter while they are dragged with the mouse pointer

### ISSUE THREAD

**Issue by maxigaz** [rncbc/qtractor#346]
Here's a screencast I recorded while moving a slider from side to side in the native UI of Surge XT (LV2), when loaded in Qtractor:

https://user-images.githubusercontent.com/10419911/172236101-87802890-0900-4988-9af2-7b195ef7197a.mp4

It also happens in the LV2 version of Vitalium and Odin2, but not the VST versions.

Also, I've never experienced this issue in Ardour and Carla.

**Comment by windowsrefund** [comment]
I use the lv2 version of Odin2 and have never seen this.

**Comment by maxigaz** [comment]
It's butter smooth in Carla.

By the way, the version of Qtractor I have is 0.9.26.34git.676c3f (compiled from master).

**Comment by windowsrefund** [comment]
OK, looks like the issue is qtractor specific as I was just able to reproduce it myself. As mentioned earlier though, I've never seen this because I outsource all of my synths/etc to Carla by way of busses.

```
dpkg -l |grep qtractor
ii  qtractor                                                    0.9.26.34git.676c3f-69.1
```

**Comment by rncbc** [comment]
not sure if it fixes or makes it worse
please test qtractor >=  0.9.26.36git.[30bd72](https://github.com/rncbc/qtractor/commit/30bd72c7)
watch out for any illusive side-effects esp.re.undo and redo and everything else :) (applies to LV2 plugins only;))
byee

**Comment by maxigaz** [comment]
I've switched to Ardour as my main DAW/sequencer, so I've only tested it briefly.

All I can say for now is that I can still reproduce the original issue.

**Comment by rncbc** [comment]
what about qtractor >= 0.9.26.37git.[749d91](https://github.com/rncbc/qtractor/commit/749d916a) ?

**Comment by windowsrefund** [comment]
I'd be happy to test once 0.9.26.37 is in the repo. I just upgraded to .36 and still see the issue.

**Comment by maxigaz** [comment]
> what about qtractor >= 0.9.26.37git.[749d91](https://github.com/rncbc/qtractor/commit/749d916a) ?

It looks like you fixed it this time. :) Thank you!
