### ISSUE TITLE
MIDI note doesn't fit into the grid properly when drawn (Fedora 36 RPM from OBS repo)

### ISSUE THREAD

**Issue by Crono23** [rncbc/qtractor#367]
Hi! I'm loving the program so far, but I have one issue when I try to draw MIDI using the snap feature. The notes I draw doesn't fit into the grid, it is off by a small amount of time. Thanks!
Qtractor version: 0.9.29.29git
![Screenshot from 2022-11-07 16-39-44](https://user-images.githubusercontent.com/88884864/200279422-a2d5c6da-3d6d-4ac8-b0fc-67ef62a544ac.png)
Edit: I'm using Fedora 36, with the .rpm package from [this repo](https://software.opensuse.org/download/package?package=qtractor&project=home%3Arncbc).
Edit 2: Added version number.

**Comment by rncbc** [comment]
can you tell whether this latest AppImage version (which probably equals the Fedora 36 .rpm), suffers from the same issue: 
https://download.opensuse.org/repositories/home:/rncbc:/apps/AppImage/qtractor-latest-x86_64.AppImage
cheers

**Comment by Crono23** [comment]
> ps. when reporting issues please always refer to which actual version the symptoms are occurring. thanks

Sorry I forgot about that. Thanks for the reminder!

> can you tell whether this latest AppImage version (which probably equals the Fedora 36 .rpm), suffers from the same issue?

Yes it suffers from the same issue, here
![Screenshot from 2022-11-08 00-03-44](https://user-images.githubusercontent.com/88884864/200371277-06ade49b-3a5b-42e9-ae94-75337299d291.png)

**Comment by rncbc** [comment]
pretty old regression fix is on qtractor >= 0.9.29.31git.[700acf](https://github.com/rncbc/qtractor/commit/700acfe)

please download and test either/both the fc36.rpm and the (latest).appimage (same link as above).

**Comment by Crono23** [comment]
Can confirm it works on 0.9.29.31git.700acf. Thank you very much :)
![Screenshot_2022-11-08_13-05-29](https://user-images.githubusercontent.com/88884864/200489773-78752bcf-3f75-4943-abac-041734e497d3.png)
