### ISSUE TITLE
JackTransport button

### ISSUE THREAD

**Issue by tjingboem** [rncbc/qtractor#37]
i would like to do a request for a button that toggles yes or no for JackTransport setting.

We have set Qtractor JackTransport to "FULL", because we sync the computer that is running QTractor to another computer (the Master), using JackTransport.
Having a button would give quick access to the mode where one can do some work privately or get connected to the other computer.

The setting to Slave, Master or Full can already have been (F12) - the button chooses None or Slave/ Master/Full.

**Comment by rncbc** [comment]
yay! this might have come to a close with this one: https://github.com/rncbc/qtractor/commit/3913ee7

cheers

**Comment by trebmuh** [comment]
Is it a right time to close this issue maybe?

**Comment by rncbc** [comment]
absolutely.

**Comment by tjingboem** [comment]
yes sorry -  forgot to mention you could close this as far as we are concerned. Thanks very much for this important (for us) update!
