### ISSUE TITLE
MIDI rounding error, note not played

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#371]
commit 49dd246bd9bd9e1a1537e5eb087cfd3a4d3988b8
(I don't know when the issue showed up first)

![1](https://user-images.githubusercontent.com/5550538/210168906-35d15363-c90a-49cf-99f6-05b31067b789.jpg)

The left window is the original clip, the right window is the copied/linked clip. It's used for a kick drum in drumkv1. As you see the durations are not exactly equal. Some durations are 240 and then the 2nd note on the marked two notes in the right window is not played (or the note off comes too quick).

![2](https://user-images.githubusercontent.com/5550538/210168912-c4127c9e-8c99-492d-a1ed-bb13a5176b49.jpg)

Wenn I shorten the first of the two notes in the right window then the 2nd note is played correctly.

When I change the track's type to drums then the 2nd note is played, probably because of the suppression of the note-off.

This happens on other tracks with synth plugins as well, so some notes are not audible.

Further investigation shows that not only copied/linked clips are effected. Even perfectly quantized clips have some different durations.

**Comment by rncbc** [comment]
can you share one and just one of the original MIDI files (.mid) that shows these rounding errors? maybe "schwerelos-Kick-7.mid" ?)

**Comment by suedwestlicht** [comment]
This is a nasty heisenbug, a few hours later the notes aren't cancelled anymore in the kick clip. 

Existing old session:
Quantizing duration re-introduces the error sometimes, sometimes in a copy on another location in the same track.
Even drawing a new clip eg. with beat/4 snap shows that problem.
Copying an existing clip doesn't make the copy "linked".
![same_session_new_clip](https://user-images.githubusercontent.com/5550538/210183981-fb1d9d87-993e-4ba4-bc2c-2f9ae0c35e8a.png)

Completely new session:
Drawing a new clip works ok. No cancelled notes. Copying a clip makes the copy "linked" as it should be, even after save/reload.

But duration is 0.0.479 after loading and 0.0.480 after quantizing. Saving, restarting Qtractor and loading shows 0.0.479 again. Maybe no real issue but a bit strange anyway.
![new_session_after_loading](https://user-images.githubusercontent.com/5550538/210184124-785126bb-7215-4b6c-841b-a7ae20b4f778.png)
![new_session_after_quantizing](https://user-images.githubusercontent.com/5550538/210184130-83cf7382-dad9-4538-937b-6e08d34e852a.png)

I am getting confused. I am not sure if I nailed the problem correctly. I guess I have to workaround the problematic clips in my session by using drums-mode where possible and editing the notes' ending manually.

**Comment by rncbc** [comment]
may you try this from develop branch?  https://github.com/rncbc/qtractor/commit/a96e4bb

**Comment by suedwestlicht** [comment]
Thx, this fixes "But duration is 0.0.479 after loading and 0.0.480 after quantizing. Saving, restarting Qtractor and loading shows 0.0.479 again. Maybe no real issue but a bit strange anyway."

It doesn't fix the strange quantizing issue (some .479, some .480, some cancelled notes when quantizing) with
[schwerelos-Synth_Bass-5.mid.zip](https://github.com/rncbc/qtractor/files/10332573/schwerelos-Synth_Bass-5.mid.zip)

**Comment by rncbc** [comment]
and now this one may you try this from develop branch?  https://github.com/rncbc/qtractor/commit/b15d0a4
(you'll prolly need to `git reset --hard origin/develop` before that, sorry)

**Comment by suedwestlicht** [comment]
Nearly.

Quantizing makes all durations to .480 and no note is cancelled.

But saving/restarting Qtractor/reloading shows some .479 and some cancelled notes.

**Comment by suedwestlicht** [comment]
Still a bit strange.

Making all notes a bit shorter than .479
Save clip & song
Restart Qtractor
Reload song
Quantize duration to /8
All durations are .480
Save clip & song
Restart Qtractor
Load song
All durations are .480
No cancelled notes
Copy clip
Copied clip is not linked
Some durations in copied clip are .479
Some cancelled notes in copied clip

**Comment by suedwestlicht** [comment]
A MIDI clip imported into a new session makes no trouble. It can be quantized, works properly and copied clips are recognized as "linked".

Both sessions have the same time properties.

What could possible make the difference?

**Comment by rncbc** [comment]
please tell which runtime is you working out and collecting eveidence: whether v0.9.30 or v0.9.30.1 (develop) ?

**Comment by suedwestlicht** [comment]
As always on my old Xubuntu 16.04.

The old session was created at least a year ago with an older version of Qtractor.

I use at the moment  v0.9.30.1 (develop)

**Comment by suedwestlicht** [comment]
Additional information:
In the existing session a copied clip doesn't have the same length as its source.

source clip: 1607442
copy 1: 1607443
copy 2: 1607448

That might be the reason why the copies are not recognized as linked.

**Comment by rncbc** [comment]
good catch. are those figures in frames?

**Comment by suedwestlicht** [comment]
They are from the qtr file, probably those 960 ticks per beat.

**Comment by rncbc** [comment]
nope. in the .qtr file all clip-lengths are in frames.

**Comment by suedwestlicht** [comment]
ok, then the clip-lengths are in frames.

**Comment by rncbc** [comment]
can you please provide the minimal session file with those 3 midi clips only? thanks

**Comment by rncbc** [comment]
thanks. can you now try with the fix in v0.9.30.7git.[c9c979](c9c9790) ?

**Comment by suedwestlicht** [comment]
This has fixed:
- copied clips are now recognized as linked

It has not yet fixed:
- different lengths:
  source: 1607442
  copy1: 1607443
  copy2: 1607442
- in the copied clips there are still cancelled notes when playing

[schwerelos.1.qtz.zip](https://github.com/rncbc/qtractor/files/10383317/schwerelos.1.qtz.zip)

**Comment by rncbc** [comment]
okay, let's see if this one nails it: v0.9.30.8git.[e27789](e277892f6) 

note that the different lengths are already there in the original file, coming from v0.9.29 .

**Comment by suedwestlicht** [comment]
Copying a midi clip again makes the copies perfect, both lengths in the tqr/qts and in the event window

But there is e new bug introduced when loading old sessions that affects midi tracks from about number 11 on:  midi clips have wrong contents. I had HiHat patterns from track 10 in track 11's kick drum clips.

**Comment by rncbc** [comment]
> But there is a new bug introduced when loading old sessions that affects midi tracks from about number 11 on: midi clips have wrong contents. I had HiHat patterns from track 10 in track 11's kick drum clips.

that's horrific! you only notice now with this v0.9.30.8 or was it already there before that? does v0.9.29 do the same? please try to find some pattern on the strange overriding behavior: specifically about file-names(.mid), track and channel numbers, anything that might collude to that wrong doing.

for example: if you isolate to only having former tracks #10 and #11 as track #1 and #2, saving it to a new session (preferably doing it on v0.9.29, supposing it loads them right in the first place) and then reload it again, what happens?

**Comment by suedwestlicht** [comment]
b06c9f4dbc5e7661acd7c70b3cf6100cde075549 was ok.
![ok](https://user-images.githubusercontent.com/5550538/211639681-475ed3fb-eae9-4c86-8544-3f998d86472c.png)

c9c9790dc06896cfc6f3245c83b09a8245b65fe4 introduced the new bug.
![not_ok](https://user-images.githubusercontent.com/5550538/211639728-ad4e2779-8a19-400f-808f-faebed60f557.png)

It happens as well with a stripped down version with only those 2 tracks.
[schwerelos_2_tracks.qtz.zip](https://github.com/rncbc/qtractor/files/10386029/schwerelos_2_tracks.qtz.zip)

e277892f6c3f6fb644a9a78d6ac48f89fe618ffe still has the new bug.

**Comment by rncbc** [comment]
my bad--I should spank myself in shame to have dropped that one single but important source line by mistake...

fixed now in 0.9.30.10git.[523b70](https://github.com/rncbc/qtractor/commit/523b701)

thanks a lot for your patience

**Comment by suedwestlicht** [comment]
Thank you Rui

**Comment by suedwestlicht** [comment]
There are still some rare rounding errors in the copied clips (in the events window) but I think that's just a minor flaw and has no effect on the basic functions.
![a](https://user-images.githubusercontent.com/5550538/211788179-23828aaf-a9eb-4b7e-a744-0c0b8365e94b.jpg)

**Comment by suedwestlicht** [comment]
Didn't find other issues when loading/saving other songs. Looks good and backward compatible.

**Comment by rncbc** [comment]
thanks, meanwhile I've streamlined and generalized the whole rounding business and it now seems to even get the issues you found in https://github.com/rncbc/qtractor/issues/371#issuecomment-1378567920

it maybe all fixed in this new delivery v0.9.30.15git.[d2e59b](https://github.com/rncbc/qtractor/commit/d2e59b5)

please test it thoroughly with the usual safety guards (backup, backup, etc. ;))

**Comment by suedwestlicht** [comment]
Yep, the minor flaws in the event window are fixed. I can't find any other issues.

Thanks, Rui.

**Comment by rncbc** [comment]
keep an eye on it, for a while though ;)
wholly thanks, a lot
