### ISSUE TITLE
piano roll painting issue

### ISSUE THREAD

**Issue by danboid** [rncbc/qtractor#375]
I'm getting lots of bits of red lines when I'm editing the qtractor piano roll. They look like artefacts of the play head cursor and they gets worse when the play head is active.

I'm running the qtractor 0.9.31 package from the Debian Testing repos using gcc 12.2.0, Qt 6.4.2 and NVIDIA driver 515.86.01

Here is a video of what they look like:

https://user-images.githubusercontent.com/1429783/216828576-247e7dbd-51b1-4db7-a353-4254cccb47df.mp4

**Comment by danboid** [comment]
OK gh didn't like my video so I uploaded it to YT:

https://youtu.be/WH8Lxhp3Cqs

**Comment by rncbc** [comment]
the desktop screen seems scaled up; please try to cope with the exact native resolution first (1920x1080) then chose some other scale factor

**Comment by danboid** [comment]
Sorry Rui, I don't understand your suggestion. I am not using MATE's hidpi scaling if that's what you're suggesting is causing the problem.

**Comment by danboid** [comment]
I think I see what you mean now, Qt apps seem to be scaled. I think this might've been caused by me using qt5ct to try setting a dark mode in qt apps. I've tried setting it back to what I thought was the default although I currently still have the same issue.

**Comment by rncbc** [comment]
qt5ct should not interfere with qt6 apps anyhow

please check your desktop settings for a scaling factor being applied (eg. QT_SCALE_FACTOR > 1.0)

**Comment by danboid** [comment]
OK this is a MATE specific bug as I don't have the problem when I run qtractor under XFCE. I've tried your suggestion and a couple of gsettings options but nothing has fixed it under MATE yet, qtractor (and qjackctl) insist on launching scaled.

**Comment by danboid** [comment]
dan@zbook:~$ gsettings get org.mate.interface window-scaling-factor-qt-sync
false
dan@zbook:~$ gsettings get org.mate.interface window-scaling-factor 
1

**Comment by danboid** [comment]
Thanks for your help Rui, lets punt this over to the MATE devs.

https://github.com/mate-desktop/mate-session-manager/issues/302
