### ISSUE TITLE
offset

### ISSUE THREAD

**Issue by tjingboem** [rncbc/qtractor#38]
can the Time line, that starts at "1", get an offset option?

This would allow the time line to start for example with "0". 
In our case, this would correspond to "0" set on JackTransport.

With a tempo and beat setting of 30 4/32, the playback head AND the JackTransport would show the same number - much less confusion there :)

**Comment by rncbc** [comment]
On 09/05/2016 09:23 AM, Menno Knevel wrote:
> can the Time line, that starts at "1", get an offset option?
>

please note that the top time-ruler scale units is numbered and divided 
after musical time, BBT (bar.beats.ticks), it is not about frames nor 
real-time units.

the musical position that corresponds to frame 0 or time 00:00:00.000 is 
noted exactly as 1.1.000, for first bar, first beat, tick 0.

hth.
cheers
-- 
rncbc aka. Rui Nuno Capela

**Comment by tjingboem** [comment]
okay, i understand this from a musical perspective.
No problem, we just take the JackTransport time - 1 . Then it corresponds to the musical time of QTractor.

thanks!
