### ISSUE TITLE
automation gets switched on when it shouldn't

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#382]
Observed on recent Qtractor from git (0.9.31.34git.929f98.dirty)
Using: Qt 5.5.1

1.) goto mixer
2.) right-click on a volume or pan fader (midi or audio track)
3.) set Automation on
4.) right-click again on the fader
5.) set Automation off
6.) right-click again on the fader
-> Automation is set on although it shouldn't

**Comment by rncbc** [comment]
you're not actually _switching_ automation on and off; rather, you're just _selecting_ the automation curve to show up or not, that's the deal.

the first time you check the "Automation" right-click menu item, the new automation curve is created and selected to display on the timeline track view; next time you raise the same right-click menu again, the automation curve is immediately selected into view and the check mark will be on there alright but saying there's automation defined for that subject and it's currently selected.

it's doing it as always have been :)
cheers

**Comment by suedwestlicht** [comment]
OK, thx Rui.
