### ISSUE TITLE
Send MIDI start/stop

### ISSUE THREAD

**Issue by TatriX** [rncbc/qtractor#384]
Hey!

I cannot find a way to make qtractor send midi start/stop messages when I start/stop the transport.
I'm syncing qtractor to external midi clock, and start/stop coming from the hardware sequencer works, but not the other way around.

Do I need to enable it somehow?
Thanks :)

**Comment by rncbc** [comment]
yes: please check the MIDI **SPP** option.

**Comment by TatriX** [comment]
It is set to Duplex. I've also tried Input, but no luck.

**Comment by TatriX** [comment]
Oh, I had to enable incoming midi clock on the device. Sorry, my bad..
