### ISSUE TITLE
MIDI off is not sent on transport stop

### ISSUE THREAD

**Issue by TatriX** [rncbc/qtractor#385]
Hi again!
I'm sending midi notes to the external device. When I stop the transport in the middle of a note, no note off message seems to be send to the device resulting in a hanging note.

Here's what midi traces on the device shows:
<img width=300 src="https://user-images.githubusercontent.com/703150/228351800-dc0628f2-e8b8-4660-86bd-aa0f01fadbce.png">

You can notice that A2# note on was sent, but no corresponding note off event was sent when I pressed spacebar.

**Comment by rncbc** [comment]
correct; an  all notes off is (CC#123) sent instead; the device should shut off all playing in that channel in response; note-off messages are not sent when playback stops whatsoever.

**Comment by TatriX** [comment]
Unfortunately hardware I have for whatever reason ignores all-notes-off. I don't know if it's on [purpose](http://midi.teragonaudio.com/tech/midispec/ntnoff.htm) or not. What I know is that my [sequencer](https://squarp.net/pyramid/) is sending individual note-off events when I press stop. Maybe it's doing that to overcome the all-note-off quirks or the sequencer itself it to blame. This is quite an issue for me, because I have to trigger midi-panic almost every time I stop the transport.

**Comment by TatriX** [comment]
Just checked Bitwig: it sends individual note-off events on transport stop.

**Comment by rncbc** [comment]
qtractor doesn't and that's a fact for over more than 15 years now.

**Comment by rncbc** [comment]
you may now test this feature from  the new [xnoteoffs](https://github.com/rncbc/qtractor/tree/xnoteoffs) branch

**Comment by TatriX** [comment]
Oh, that's amazing, thank you!
Just gave it a shot - it does work!
One issue I've found is that if you stop the transport after the loop wraps, noteoffs are not sent.

**Comment by rncbc** [comment]
> One issue I've found is that if you stop the transport after the loop wraps, noteoffs are not sent.

yes, that has been addressed just a few moments ago in https://github.com/rncbc/qtractor/commit/161a4b4

thanks

**Comment by TatriX** [comment]
Works like a charm, thank you!

**Comment by rncbc** [comment]
merged/squashed into develop and master; branch xnoteoffs deleted.

**Comment by davidhealey** [comment]
I'm getting hanging notes when sending MIDI out to soft-synths hosted in Carla. In the MIDI monitor I am seeing some notes are not getting note offs when transport is stopped. The same MIDI doesn't hang when triggered from Ardour.
