### ISSUE TITLE
Clips play back at the wrong time

### ISSUE THREAD

**Issue by alandmoore** [rncbc/qtractor#40]
Qtractor periodically starts playing back clips at the wrong time.

This has happened to me on many versions of qtractor, on different operating systems with different audio hardware.

It tends to happen more when I have a more audio tracks with more edits.

It doesn't seem to happen when I play a track from the beginning, only when I play it from somewhere in the middle of the song.

It doesn't happen consistently.  I can't reliably reproduce the problem, it just happens randomly.

I have noticed that when a clip gets "dislocated" like this, it will continue to be so even if I start and stop the track.  The only was to "relocate" the clip is the manually reposition the playback cursor.  Then things playback correctly.

It seems like generally the clips are playing back earlier than they should.

Sorry that this is a fairly vague bug report.

**Comment by rncbc** [comment]
On 09/09/2016 08:31 PM, Alan D Moore wrote:
> Qtractor periodically starts playing back clips at the wrong time.
>

yes it might happen... reasons for this might be one or all of the 
following:

- underpowered and/or loaded machine or system;
- audio files sample-rate don't match jackd's and sample-rate conversion 
is set to highest quality (too cpu intensive);
- audio clips are time-stretched to insane ratios;
- audio files are of the mp3 format;

byee
-- 
rncbc aka. Rui Nuno Capela

**Comment by alandmoore** [comment]
The only one that could apply in my case is #1.  I'm using a Core Duo machine.  When my track is playing qtractor is using between 50% and 80% of each core on average.  Does using flac vs wav make a difference?
