### ISSUE TITLE
Feature request: display summed-up latency

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#410]
In each track's setting I can switch on latency compensation.

![Bildschirmfoto_2023-09-16_12-28-57](https://github.com/rncbc/qtractor/assets/5550538/9cde6aa8-c717-4111-bfd6-64d5412cc13f)

A display of the summed-up latency for all *active* plugins in this track would help identify plugins that don't report their latency properly.

**Comment by rncbc** [comment]
ack. should make it on develop branch soon.

**Comment by rncbc** [comment]
in a9191a5 [develop] branch

test && tell
thanks

**Comment by suedwestlicht** [comment]
Display works fine, tested with LSP Plugins Beat Breather (huge latency) and Autotalent on a snare track.

But the latency compensation doesn't seem to work when I switch it on for this track.

**Comment by rncbc** [comment]
> But the latency compensation doesn't seem to work when I switch it on for this track.

did it work earlier before?

**Comment by suedwestlicht** [comment]
I made a session with 3 audio tracks and the autotalent plugin. Latency compensation works ok.

I'll investigate further.

[Latency-Test.qtz.zip](https://github.com/rncbc/qtractor/files/12656471/Latency-Test.qtz.zip)

**Comment by suedwestlicht** [comment]
I added a MIDI track with drumkv1.

The MIDI track's latency compensation is active. In the loop the first note is missing as it should. But it seems that the amount of time the track is played "earlier" is not enough.

Switching all autotalent plugins off shows that the audio tracks and the midi track are in sync.
[Latency-Test.qtz.zip](https://github.com/rncbc/qtractor/files/12656953/Latency-Test.qtz.zip)

I noticed that this setup makes Qtractor unstable. Sometimes it crashes after loading or playing. In fact I couldn't load and play the attached session again. I guess it's something to do with the latency compensation switched on.

**Comment by rncbc** [comment]
> MIDI track that's not (fully) compensated"

what you mean?

probably latency compensation doesn't work seamlessly at loop turnarounds... is that it?

**Comment by suedwestlicht** [comment]
For the MIDI track with drumkv1 the latency compensation doesn't work at all.

[simplescreenrecorder-2023-09-19_12.25.58.mkv.zip](https://github.com/rncbc/qtractor/files/12658760/simplescreenrecorder-2023-09-19_12.25.58.mkv.zip)

**Comment by rncbc** [comment]
well, i'm affraid the latency compensation on MIDI tracks wasn't working at all before, so sorry :S

the latency compensation has to be reviewed and probably completely overhauled...
maybe in a brand new issue?

**Comment by suedwestlicht** [comment]
Yes. "Feature request: display summed-up latency" works fine. Task completed :)

Thx Rui.

**Comment by suedwestlicht** [comment]
There is still a little flaw updating the status. Switching a plugin on/off in Qtractor's Track->Plugins window updates latency but not in the plugin's dialog.

[display_latency.mkv.zip](https://github.com/rncbc/qtractor/files/12701355/display_latency.mkv.zip)

**Comment by rncbc** [comment]
yeah, right, just click on the latency display to refresh/update

**Comment by suedwestlicht** [comment]
Cool. I never thought that the latency display is clickable.

How about making it change its background color when hovering - like "Latency compensation". It would then be easier to notice that it's clickable.

**Comment by rncbc** [comment]
now that you know, is it really necessary? besides, it _depends_ on the widget style in charge, some make it like so, others just don't... you decide ;)

**Comment by suedwestlicht** [comment]
We can keep it as a secret :)

**Comment by suedwestlicht** [comment]
Thx again.
