### ISSUE TITLE
Plugin latency compensation doesn't work with MIDI tracks

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#411]
[Latency-Test_3.qtz.zip](https://github.com/rncbc/qtractor/files/12669867/Latency-Test_3.qtz.zip)

Maybe it can't be resolved by playing the MIDI track a bit earlier (as done for audio tracks) because I am afraid that samples/milliseconds cannot be converted in BBT due to the fact that tempo can change.

So another approach could be delaying OTHER tracks' audio by the maximum latency over all tracks (minus the latency of a given track when latency compensation is switched on).

**Comment by rncbc** [comment]
maybe fixed in b9644232 [develop] branch.

**Comment by suedwestlicht** [comment]
It works. Thx Rui

**Comment by suedwestlicht** [comment]
I think I should close this issue as it is fixed.
