### ISSUE TITLE
Audio bus is not passing signal

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#412]
Disclaimer: I'm only a day or into a JACK+PA switch to Pipewire. That said, everything outside of Qtractor appears to be running nice and smooth. 

Audio Setup:

```
> inxi -A
Audio:
  Device-1: Intel Cannon Lake PCH cAVS driver: N/A
  Device-2: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
    driver: N/A
  Device-3: Texas Instruments PCM2902 Audio Codec type: USB
    driver: hid-generic,snd-usb-audio,usbhid
  Device-4: Midiplus Co X6mini type: USB driver: snd-usb-audio
  Sound API: ALSA v: k6.5.5-1-liquorix-amd64 running: yes
  Sound Server-1: PipeWire v: 0.3.65 running: yes
```
Qtractor Version: 0.9.35.16

Qtractor Setup: 1 added audio bus (Mode: Duplex, Monitor: enabled) and 1 added MIDI bus (Mode: Duplex, Monitor: enabled). These are used to route to and from Carla.

As a baseline, the most simple of all routing can be heard:

![NM1-1](https://github.com/rncbc/qtractor/assets/512222/835151ac-9752-4170-8017-03224bac6b23)

Using the additional NM1 audio bus exclusively can also be heard:

![NM1-2](https://github.com/rncbc/qtractor/assets/512222/58794bef-8700-42fc-ac36-056f4eaea0a4)

However, the following can not be heard (or seen in the mixer). Audio signal is simply not being passed from the NM1 bus to Master.

![NM1-3](https://github.com/rncbc/qtractor/assets/512222/1fdc5f07-e5c4-4116-b6d0-5bee53eab8aa)

![Mix-3](https://github.com/rncbc/qtractor/assets/512222/5faf18fb-deb8-45a2-85ba-6a75606b9258)

Looking through the issues, I spotted [405](https://github.com/rncbc/qtractor/issues/405). Of course, I don't expect I'd be the one reporting such a basic issue after so much time has passed but figured I'd mention it.

Looking to explore possibilities in order to avoid having to go back to my old setup.

**Comment by rncbc** [comment]
plese refer to this old comment [re. 'Subgroup' problem](https://www.rncbc.org/drupal/comment/6497#comment-6497)

this would probably work _iif_ the target input-bus is listed after the source output-bus, in processing order...

and even so this wouldn't work in  in genuine-jack, due to _ zero-copy_ buffer optiimization, it probably works alright in pipewire-jack substitution, as the said optimization is not there (or it wasn't last time i've checked).

**Comment by windowsrefund** [comment]
I'll certainly study the thread and report back but this worked perfectly for years using my old JACK setup. Are we saying Pipewire as a backend somehow "exposes" this problem?

**Comment by windowsrefund** [comment]
OK, I've reverted to my original jack+pa setup and can confirm everything works as expected. 

![Workie](https://github.com/rncbc/qtractor/assets/512222/41b116ec-98b1-4333-943d-a623737de768)

![Mix](https://github.com/rncbc/qtractor/assets/512222/56fdbfa2-4788-4473-a56c-578eb1623ed4)


My take-away here is that for whatever reason, it is not practical to try to use Qtractor against a Pipewire backend. This is true despite having upgraded the current ubuntustudo packagee (0.3.65) to the latest  (0.3.79 provided via the project's upstream PPA.

**Comment by rncbc** [comment]
it's not about pipewire-jack vs. genuine-jack, at all, although using one or another may lead to different results in cases like this one in particular.

see [re. Qtractor : routing problem](https://www.rncbc.org/drupal/comment/6966#comment-6966)

the rule of fact to keep in mind here:
> in general, **it is NOT advisable to connect any jack-client**--and qtractor in particular--**outputs directly into any of its own inputs**.
disregard this advice and _undefined behaviour_ ensues... as you may now know that's evident it behaves differently between pipewire-jack's and genuine-jack's implementations--it's not the fault of either one but yours disregard of that (pretty old) advice.

cheers

**Comment by windowsrefund** [comment]
I'm sorry but what? You're stronly advising not to use a bus for........... bussing a signal? Are you serious?

**Comment by rncbc** [comment]
no

I'm only seriously advising to avoid connecting output-buses directly to input-buses.

as you know by now, it just doesn't always work reliably, even on different jack-API implementations.

**Comment by windowsrefund** [comment]
I'm just blown away by this answer.

**Comment by rncbc** [comment]
you're may feel this is all BS as sure it was all working for years in your particular case; but the writing is on the wall, so to speak: what is supposedly working might just not guaranteed to work if at all in the future, specially on  genuine-jack or pipewire-jack versions.

it can even happen the inverse: it stops working on genuine-jack and starts on pipewire-jack; or none at all or both, kinda russian-roulette.

back to your case: may I ask what's the real purpose for you to make a _direct_ loop-back from NM1-out into Master/in in the first place? what are you willing to achieve with that ? remember the _directly_ saying? if you insert a(ny) jack-client application in between (eg. NM1-out -> jack-app -> Master/In) the whole thing doesn't apply and it shall work on all cases and accounts, now and in the future :)

**Comment by windowsrefund** [comment]
This is so nuts to have to explain. The images clearly show the flow of things. Now you're talking about looping back to Carla again in order to try and tell me not to use a mixer like a mixer?

**Comment by rncbc** [comment]
> What is this hypothetical "jack-app" you're talking about?

not hypothetical: any  jack audio application will do as long it have audio ins and outs.

**Comment by windowsrefund** [comment]
Which brings me back to my original point? From a JACK perspective, Qtractor is supposed to be a client.

**Comment by rncbc** [comment]
> Which brings me back to my original point? From a JACK perspective, Qtractor is supposed to be a client.

exactly, noyt supposed to be the only one ;)

**Comment by windowsrefund** [comment]
There are no hard feelings (never were) but TBH, I'm left with the distinct feeling that this decade-long issue or bug has been left largely not understood. Despite moving to Pipewire, I'll probably just avoid using its JACK layer and run jackd going forward.

**Comment by G3N-es** [comment]
>  remember the _directly_ saying? if you insert a(ny) jack-client application in between (eg. NM1-out -> jack-app -> Master/In) the whole thing doesn't apply and it shall work on all cases and accounts, now and in the future :)

I enter the discussion because I consider the problem to be real and annoying.

I can think of a simple solution: Why doesn't Qtractor create this app-jack bridge transparently to the user?

In other words, why not use inserts instead of buses.
If the problem is that it adds a bit of latency, in most cases it will be unnoticeable, but it would ensure that it works.

I don't know if I've made myself clear.
