### ISSUE TITLE
Change icon theme

### ISSUE THREAD

**Issue by AlexHCC** [rncbc/qtractor#420]
Hi,
I am trying to create a custom high contrast theme, and I can change the theme colors, but as far as I can tell there is no easy, built in way to change the icons to look different. Is there any plan to support different icon sets such as monochrome etc.?
I understand that creating custom icons from scratch is unrealistic in terms of scope, but at least is there an easy way to change them to a different installed icon pack?

**Comment by rncbc** [comment]
>  is there an easy way to change them to a different installed icon pack?

nope; nor easy: all icons are _hard-coded_ and/or project resources on their own.

**Comment by AlexHCC** [comment]
Oh, I see. So the only way is to manually change the src/images to custom ones.
But even if I create new ones, there is no system in place to change between them. This may be something worth considering in the future, if enough demand/resources are available.
Thanks anyways!
