### ISSUE TITLE
Calf plugins' GUIs won't open

### ISSUE THREAD

**Issue by tcrass** [rncbc/qtractor#423]
# Version

OS: Mainly Debian Testing, with a little bit from Debian Sid
qtractor: 0.9.36-1 (the version currently in both Testing and Sid)

# Problem description

When double-clicking any Calf plugin in the "Bus" section of a track's header, the plugin's GUI won't open. In fact, nothing happens -- no crash, no error message in neither qtractor nor the console window it was started from. Other plugins' GUIs open just fine (tried Helm, Dexed, QMidiArp). Calf plugins work flawlessly in e.g. Carla or Ardour.

**Comment by tcrass** [comment]
Just realized that in qtractor's "About" dialog it says "LV2 Plug-in UI GTK2 native support disabled" and "LV2 Plug-in UI GTKMM2 native support disabled". Maybe this is the cause of the issue? If so, does anyone know if this is this qtractor's new build default, or if it is a Debian-specific configuration?

**Comment by rncbc** [comment]
probably debian's specific: it should have been with libgtk2.0-dev and  libgtkmm-2.4-dev available during build.

**Comment by tcrass** [comment]
> probably debian's specific: it should have been with libgtk2.0-dev and libgtkmm-2.4-dev available during build.

Ah, pitty... So I guess I'll submit a bug report there.
