### ISSUE TITLE
Debian build from git fails

### ISSUE THREAD

**Issue by toadzroc** [rncbc/qtractor#435]
OS: AVLinux (AVL-MXDE) 23.1, with Pipewire installed by default.

The latest git fails to build (debian), with the following error message:

dpkg-shlibdeps: error: no dependency information found for /usr/lib/x86_64-linux-gnu/pipewire-0.3/jack/libjack.so.0 (used by debian/qtractor/usr/bin/qtractor)
Hint: check if the library actually comes from a package.
dh_shlibdeps: error: dpkg-shlibdeps -Tdebian/qtractor.substvars debian/qtractor/usr/lib/qtractor/qtractor_plugin_scan debian/qtractor/usr/bin/qtractor returned exit code 255
dh_shlibdeps: error: Aborting due to earlier error
make: *** [debian/rules:3: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

As far as I can tell, all the required dependencies are installed, including libpipewire-0.3-dev

I have run ldconfig..

**Comment by rncbc** [comment]
and what about pipewire-(lib)jack-dev ?

**Comment by toadzroc** [comment]
There is no pipewire-jack-dev in the repository, according to apt.. Only pipewire-jack, which is already installed.

There is also libjack-jackd2-dev, which is already installed.

I've just built Qtractor natively, and it built ok. Cmake shows the jack module is recognized.
