### ISSUE TITLE
Bad line break in info window

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#442]
![Bildschirmfoto_2024-03-23_11-38-31](https://github.com/rncbc/qtractor/assets/5550538/2d6e8c66-64c9-4537-8b0f-6c91997bf325)

**Comment by rncbc** [comment]
might be related to font management and qt build; otherwise it doesn't occur here.
![image](https://github.com/rncbc/qtractor/assets/1554353/f8b06485-2fa6-4189-9713-d6ea45f01db4)
