### ISSUE TITLE
Insert Send display issue (and maybe more)

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#445]
I had some problems with an existing session when inserting an Insert Send into the Master Audio Bus. It worked fine, but after saving/loading the session the Insert Sends were renumbered and there were some MIDI tracks' audio bus displayed as before (e.g. "Drums") but the output went to another bus 1 position left ("e.g. Common").

I tried the whole afternoon creating a minimal session where this occurs but I failed. I noticed that type= and name= were swapped after inserting or deleting an Insert Send:

before: track type="midi" name="Pad 1"
after: track name="Pad 1" type="midi"

That should not make any difference when Qtractore loads and parses the file so I looked for another glitch that might lurk in Qtractor and I found at least a display issue. If there are more than 9 Insert Sends in a Qtractor session then the Insert Send 1 "Send" window shows other Insert Sends > 9 as well.

Maybe it's only a display problem but there might be a chance that this affects loading/parsing a session file as well.

![Bildschirmfoto_2024-05-05_18-08-32](https://github.com/rncbc/qtractor/assets/5550538/af3543ff-4d74-4dc3-ac1d-b0c42a9f9b5c)

**Comment by rncbc** [comment]
the later is just a display issue, will get fixed soon, thanks

**Comment by suedwestlicht** [comment]
Confirmed. Thx.

**Comment by suedwestlicht** [comment]
Now I got more. I could create a sample session that reveals the Insert Send bug.

It's s simple session with one MIDI track (Yoshimi) and 3 Output Buses sum1, sum2, sum3. All Output Buses go to the Master Bus. All Output Buses have an Insert Send (to itself to make it simple). The MIDI track goes to Output Bus sum2.

That works ok.

Now add an Insert Send (e.g. to itself) in the Master Bus. That becomes "Insert 4".

That still works ok.

Now save this session and reload it. The Insers are renumbered, that may be ok and intended.

- Now the MIDI track goes to sum1 instead of sum2.
- The Insert Sends' Sends and Returns are a mess.

[masterinserttest.qtz.zip](https://github.com/rncbc/qtractor/files/15247029/masterinserttest.qtz.zip)

**Comment by rncbc** [comment]
maybe fixed in https://github.com/rncbc/qtractor/commit/377c485534a0070980d69e2966df64adf90c7870

please test && tell

nb. you'll have to save it first once to reload in correct order again.

**Comment by suedwestlicht** [comment]
Yes, it's fixed. Thx Rui.
