### ISSUE TITLE
Improved legibility to all clip title labels (color contrast)

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#448]
Doesn't work always:
![Bildschirmfoto_2024-05-18_12-52-29](https://github.com/rncbc/qtractor/assets/5550538/beb4a7c4-6cf2-45f1-8ad8-b419eed487b2)

How about an attribute "Label" for a track in addition to "Foreground" and "Background"?

**Comment by rncbc** [comment]
maybe with 214685d it gets better!

**Comment by suedwestlicht** [comment]
Yes, much better. Thank you.

![Bildschirmfoto_2024-05-18_17-52-15](https://github.com/rncbc/qtractor/assets/5550538/87348720-85b8-43c5-aacd-610326d41556)
