### ISSUE TITLE
Fade In/Out curve of audio clips not properly copied

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#452]
When I copy an audio clip with linear fade in/out the copied clip gets quadratic curves.

![a](https://github.com/rncbc/qtractor/assets/5550538/211229f1-705a-4324-bf22-0b185836d4d9)

**Comment by rncbc** [comment]
fixed in 02db8f175 (v1.0.0.7+)

**Comment by suedwestlicht** [comment]
Yep. Thx Rui.
