### ISSUE TITLE
ff36c6a was not reverted correctly

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#463]
Thank you for [attempting to revert](https://github.com/rncbc/qtractor/commit/7e4caf66b9564c6a04b31e11921ce0bd62d42f2b) ff36c6a. Sadly, this was not a true 1 for 1 undoing as can be seen when comparing the diffs.

I'm guessing the attempt to revert may have been done manually? The correct (true) way to remove the commit would be to use `git revert` against the commit hash. So now, these would both be needed.

```
git revert 7e4caf66b9564c6a04b31e11921ce0bd62d42f2b
git revert ff36c6a251e9da8c0a9d16995be63255279c8282
```

**Comment by rncbc** [comment]
it isn't a reversion rather a regression, something to de-clutter unnecessary code introduced in ff36c6a

**Comment by windowsrefund** [comment]
ah gotcha
