### ISSUE TITLE
Qtractor crash after moving copied Midi regions

### ISSUE THREAD

**Issue by axel-rank** [rncbc/qtractor#465]
Qtractor 1.1.1

Create a midi region, Copy the region, Move the region --> Qtractor Crash

![Peek 2024-08-22 10-10](https://github.com/user-attachments/assets/740a85fd-d5c7-452b-8fd9-adb5d748cd21)

**Comment by rncbc** [comment]
please test whether current git head (>= v1.1.1.25git.[47b2de](https://github.com/rncbc/qtractor/commit/47b2de0ac)) does still suffer from the same crash behavior.

**Comment by axel-rank** [comment]
Sorry, I don't know how to install Qtractor Git...

**Comment by axel-rank** [comment]
Finally I managed to install Qtractor 1.1.1.30git.f7219c
The issue is fixed. No crash after moving copied midi regions anymore.
