### ISSUE TITLE
Drum Mode View gets reset after moving region

### ISSUE THREAD

**Issue by axel-rank** [rncbc/qtractor#466]
Qtractor 1.1.1
Create Midi Track, Create Region, Select Drum Mode View, Move Region, -->Drum View gets reset.

![Peek 2024-08-20 17-23](https://github.com/user-attachments/assets/c6de8bc2-60d2-47c3-9ba3-0fdc4ff1944e)

**Comment by rncbc** [comment]
fixed in >= 1.1.1.20git.[b6fd0e](https://github.com/rncbc/qtractor/commit/b6fd0e2)

thanks
