### ISSUE TITLE
bug: Auto-backward gives precedence to a marker over previous start location

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#467]
Setup
- play-head located at 34.1.000
- marker exists at 35.1.000
- auto-backward icon engaged

Test Scenario 1:
- Start playback
- Stop  before 35.1.000
- Result: play-head returns to 34.1.000 as expected.

Test Scenario 2:
- Start playback
- Stop after 35.1.000
- Result: play-head returns to 35.1.000 which is not expected.

**Comment by rncbc** [comment]
yes it's all expected, the play-head returns to the immediate previous marker, loop or punch point, edit-head or tail (blue lines) and the last started playback position (dim red line) whichever comes first in the backward direction.

**Comment by windowsrefund** [comment]
OK, so not a "bug" but I'd expect auto-backward functionality to result in the play-head always returning to the point where playback began. This is probably more of a feature request or refactor request as I'd have to think most users would share the expectation.

**Comment by rncbc** [comment]
gotcha, now in qtractor >= 1.1.1.25git.[47b2de](https://github.com/rncbc/qtractor/commit/47b2de0ac)

**Comment by windowsrefund** [comment]
Thanks! Will close this out tonight once confirmed.

**Comment by windowsrefund** [comment]
Yea. Good stuff.
