### ISSUE TITLE
Mixer outputs dialog is greedy

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#471]
Among others, the following buses exist:

- EB3
- ZEB3

Intention: Route EB3 bus to a audio insert sitting on another bus

After creating the new insert, hit the `outputs` button on the `EB3` bus strip. This shows both the `EB3` and `ZEB3` output ports when we'd really only want to see the pair associated with the bus.

**Comment by rncbc** [comment]
fixed in c2db407

thanks
