### ISSUE TITLE
Use Timebase-aware JACK API for relocation

### ISSUE THREAD

**Issue by theGreatWhiteShark** [rncbc/qtractor#474]
While using JACK Timebase support and being registered as Timebase master QTractor appends the JACK's current transport position with bar, beat, tick, tempo, measure, etc (BBT) information via `qtractorAudioEngine::timebase`. Other clients can then trigger tempo changes, relocations etc. using these BBT infos.

But when repositioning to another location QTractor does use the `jack_transport_locate()` method of the JACK API, which only sends frame information. Thus, the JACK server will drop BBT support for a single process cycle and other clients need to figure out the new transport position by frame alone (which most probably will not work correctly when they did already handled tempo or measure changes). Instead, `QTractor` should use `jack_transport_reposition()` in case it is registered as Timebase master. Using this method not just the new frame but all BBT information similar to the timebase callback will be provided.

This most probably will fix #260.

**Comment by rncbc** [comment]
done in c07595b

please test && tell
thanks

**Comment by theGreatWhiteShark** [comment]
Work's fine. Thanks!
