### ISSUE TITLE
GUI error with klangfalter LV2

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#478]
Commit 0dab37076140facbc283c9e3e663af14a1d1533b (GH issue #469) fixed the crash with Pianoteq 8 but introduced a GUI error with klangfalter LV2 file browser.

See screencast before and after the commit.

[before_and_after.mkv.zip](https://github.com/user-attachments/files/17191613/before_and_after.mkv.zip)

**Comment by rncbc** [comment]
well, that's not an error, rather a side-effect ...

what do you wish best: no pianoteq or weird-visual-klangfalter ? :)
