### ISSUE TITLE
Merging audio clips produces different results depending on jack's bufsize

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#481]
In a session that I had to run with bufsize 4094 because of many plugins I noticed that a merged audio clip didn't sound as the single clips before. The greater the bufsize, the bigger the difference.

I attach a sample session with clips merged at bufsize 128 and 8192 to make the effect more visible and audible.

The differences are produced with and witout fade outs in the original clips.

[mergetest.qtz.zip](https://github.com/user-attachments/files/17475601/mergetest.qtz.zip)

**Comment by rncbc** [comment]
yes, that's a fact, the audio clip merge operation takes sample on  buffer/period-size points over the fade-in/outs.

os that it's perfectly expected to have those different results depending on buffer-size alright (or alwrong, if that exists:)

maybe a good idea to leave fade-ins/outs out of the equation?

**Comment by suedwestlicht** [comment]
But strange things happen without fades as well.

![withoutfades](https://github.com/user-attachments/assets/dc6ce509-033a-44fc-9da9-1cb4a5d89751)

**Comment by rncbc** [comment]
well, 8192 periods are quite strange and lame, aren't they? :)

**Comment by suedwestlicht** [comment]
Great! Both with and without fades. Thanks, Rui.
![ok](https://github.com/user-attachments/assets/5804a5f9-3398-4875-80b1-e2a0eef3bc0c)

**Comment by suedwestlicht** [comment]
Qtractor on its way to a DAW :)
