### ISSUE TITLE
Small GUI annoyance

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#485]
Greets,

Not the end of the world of course but I often see the Patch and most of the Instrument columns expanded when I open a given .qtr file. Here's an example of a file I just opened:
 
![image](https://github.com/user-attachments/assets/ca96c3b8-ca89-4f99-bcdc-a7289fd5eef3)

Unfortunately, I can't reproduce this experience as setting the exposed columns and then re-opening the file does produce the desired outcome. However, given how often I've seen this, I'm thinking the condition must be an artifact of the session being in some (state) upon closing in order to produce this scenario. Just wondering to what extent others may be experiencing this? Again, not critical by any means so feel free to close this out if it is deemed unworthy.

**Comment by rncbc** [comment]
can't replicate or this might be a little side-effect to the custom widget style/sheet theme in use (nb. the lack of audio and midi tiny icons and some other nit picks...:)).

**Comment by windowsrefund** [comment]
Not seen in the wild
