### ISSUE TITLE
Truncated bus names in Add Send Bus dialog

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#486]
Some bus names are being truncated. In this screenshot, both the `SCRATCH`  and `MD1OUT` buses are impacted. I don't believe the issue is specific to casing as I've seen mixed case strings impacted as well.

![image](https://github.com/user-attachments/assets/b438ac5a-e927-4b75-b4cd-056f26e6571d)

**Comment by rncbc** [comment]
mitigated in [f0e35b4](https://github.com/rncbc/qtractor/commit/f0e35b4)

please test && tell

**Comment by windowsrefund** [comment]
Confirmed working. Thank you.
