### ISSUE TITLE
Feature Request: Double-click on slider for default value

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#487]
Greetings,

Related to the mixer strips, I know we use the middle mouse button to "reset" a given slider to default value but wonder if support for a double-click can be added? The whole middle mouse button thing just seems so dated at this point. Not important obviously but this would just feel really good as it's a common operation.

Thanks in advance

**Comment by rncbc** [comment]
implemented in [a70bff1](https://github.com/rncbc/qtractor/commit/a70bff1)

please test&tell

**Comment by windowsrefund** [comment]
So nice! Thank you.
