### ISSUE TITLE
Bug: Audio Send loses state when reordered in a strip

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#488]
I'm guessing this is a side-effect of recent functionality added involving the copying/moving of these sends across buses but it still strikes me as disruptive (and undesirable) since we're working within the same bus. Allow me to explain:

![image](https://github.com/user-attachments/assets/a2e8d044-4635-49f1-ac15-b5eaca29b8bb)

As we can see in the above screenshot, I've just added 6 inserts onto the bus. They are drawn below the last object (in this case, the Aux Send in question). Whether or not that is ideal is perhaps another discussion all-together since they're signal won't be seen. I'll leave that discussion aside for the purpose of this report and focus on the fact we know we need the Aux Send to listed last. What follows is the result of dragging that Aux Send downwards so it holds the last slot:

![image](https://github.com/user-attachments/assets/fbeeee7c-af86-45a7-869b-5ba059449cc3)

As we can see, the state of the Aux Send has been lost which means we'll need to configure it again. Where this is going to become annoying is thinking ahead to the very real scenario where these steps are going to need to be micro-managed each and every time a new instrument is added (utilizing 1 new Insert per bus) and routing is configured. In my case, I'll 1) add the new insert, 2) route a dedicated bus to the new insert, and then need to 3) adjust the position of the Aux Send and finally, 4) reconfigure the Aux Send.

So I'm hoping the Aux Send itself can either be fixed to 1) maintain its state or 2) maybe even just ensure it is always (automatically and dynamically) positioned after the last Insert on the strip (a bigger lift I'd imagine but it would solve both issues while better reflecting the actual signal routing workflow).

Thanks in advance.

**Comment by windowsrefund** [comment]
Interesting point that the state of the `Aux Bus` is only lost when it is reordered. Meaning, other elements can be reordered to taste "around" it. This makes sense and so the current work-around is:

- Add new Insert
- Right click and choose `Move up` (or drag/drop).

So programmatically, perhaps the move would shift to the creation of an `Insert` and place it onto the bus before the first `Aux Send` (if present).

**Comment by rncbc** [comment]
maybe fixed in [0dec9e0](https://github.com/rncbc/qtractor/commit/0dec9e0)

please test && tell

**Comment by windowsrefund** [comment]
Confirmed working. Thank you.
