### ISSUE TITLE
Feature Request: Add new bus below that which is used as source

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#489]
Current behavior is to simply push the new bus onto the stack resulting in it being listed at the bottom of the list. This is fine when working with a handful of buses but heavy use of the UP button comes into play when 1) many buses are put to use and 2) arrangement is important to the end user (since the order is reflected in the Mixer layout).

The low hanging fruit here is to inject the newly created bus after the bus selected prior to changing that source name and clicking `Create`. With this workflow, the end user would have complete control over the resulting order (and therefore, Mixer layout). The `Up` and `Down` buttons would become less involved as they'd really only be put to use later in life if and when a change was desired related to the Mixer layout.

Thanks in advance.

**Comment by rncbc** [comment]
experimental in [b29f59b](https://github.com/rncbc/qtractor/commit/b29f59b)

please test thouroughly--might break other things, while fixing some others.

**Comment by windowsrefund** [comment]
Confirmed working.

  * Can add new bus in desired location based on source selection.
  * Up/Down still works.
  * Bus can have all properties modified via `update` button.
  * Bus can be deleted.

Killer feature!
