### ISSUE TITLE
Feature Request: Minimize names related to Inserts and Aux Sends

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#490]
![image](https://github.com/user-attachments/assets/ec286176-f1fb-49ea-948b-dae22b653307)

The hard coded `(Audio)` string seems to be unnecessary for 2 reasons:

- I don't believe it's possible mix and match; meaning you can't create a MIDI Insert or MIDI Aux Send on a Audio bus.
- The string will most likely be cut off anyway (as seen above).

The only possible benefit I can envision would involve the use of these objects on a track where the string would help to differentiate? I don't tend to work like that so haven't proven myself correct. That said, if the extra verbosity holds some value, perhaps making use of it in the mouse-over would be enough as that would never be truncated like the strip is.

Obviously, everything here applies to the MIDI side of these objects as well.

Thanks in advance.

**Comment by rncbc** [comment]
nope, not going to fly;

while you can have only audio inserts on audio tracks or buses, you may certainly have both on MIDI tracks or buses, and there it serves the prospect well.
