### ISSUE TITLE
Feature Request: Reduce Mixer's track names up to first line break

### ISSUE THREAD

**Issue by windowsrefund** [rncbc/qtractor#491]
Just another request related to the size limitations and related side-effect of track names being truncated in the mixer...

For example, a track name is

![image](https://github.com/user-attachments/assets/6f699853-fc9c-4470-b6b7-26c21bdf9326)

which is reflected in the mixer as

![image](https://github.com/user-attachments/assets/cde94d79-4548-4bf4-ba01-2619bf51915e)

Can we just use the string up to (but not including) the first line break? Maybe center align the result?

Thanks in advance.

**Comment by rncbc** [comment]
partially done in [38eebf5](https://github.com/rncbc/qtractor/commit/38eebf5); still not centered though (you lack the tiny audio/midi icons on your own, so that horizontal center would look shifted to the right instead).

**Comment by windowsrefund** [comment]
Well damn, this looks so good. Everything is very clean looking now and I love how the entire string is shown as needed via the on-mouse-over. Awesome!
