### ISSUE TITLE
website: some minor improvements

### ISSUE THREAD

**Issue by antis81** [rncbc/qtractor#53]
Here are some minor "inconveniences" I spotted while browsing the web site. Those are small, so I don't think it is worth to open separate issues:

- [x] ~~The description to [access the Git repository](http://qtractor.sourceforge.net/qtractor-downloads.html#Git) seems to point to an old URL. Correct URL: `git clone https://sourceforge.net/p/qtractor/code` (please check)~~
- [ ] Can you please set the background colour of highlighted text to either some lighter grey or remove the shadow? It becomes unreadable:
![qtractor-website-highlight](https://cloud.githubusercontent.com/assets/440517/20556973/c4af7630-b169-11e6-9c2b-228ed8cb8ca8.png)

Keep up the great work and thanks in advance!

**Comment by rncbc** [comment]
> The description to access the Git repository seems to point to an old URL. Correct URL: git clone https://sourceforge.net/p/qtractor/code (please check)

checked the said "Correct URL" is not the Git repository address:
```
$ git clone https://sourceforge.net/p/qtractor/code qtractor_code-git
Cloning into 'qtractor_code-git'...
fatal: repository 'https://sourceforge.net/p/qtractor/code/' not found

```

> Can you please set the background colour of highlighted text to either some lighter grey or remove the shadow? It becomes unreadable

the highlighted text background color is not a property of the webpage in display, but rather a user browser's one.

**Comment by antis81** [comment]
>checked the said "Correct URL" is not the Git repository address:

Sorry, everything fine with the address for git clone. I only stumbled upon the empty website, that is being shown when opening the HTTP link in a browser. Probably Git's protocol could be used (as proposed in the project's Git repository at https://sourceforge.net/p/qtractor/code), which is slightly faster: `git clone git://git.code.sf.net/p/qtractor/code qtractor-code`. Other than that the URL works and no change is needed.

>the highlighted text background color is not a property of the webpage in display, but rather a user browser's one. 

While this is true, this is problematic on websites, that use a style, which "bites" with the standard (in this case the shadow). You can change that by using the CSS3 selector `::selection`, which allows to override the browser defaults.

**Comment by rncbc** [comment]
On 11/23/2016 11:43 AM, Nils Fenner wrote:
> While this is true, this is problematic on websites, that use a style,
> which "bites" with the standard (in this case the shadow). You can
> change that by using the CSS3 selector |::selection|, which allows to
> override the browser defaults.
> 

fixed. thanks
-- 
rncbc aka. Rui Nuno Capela
rncbc@rncbc.org

**Comment by antis81** [comment]
Oh not for that one… :) - Checked it out in Firefox (recent version 50) -> works, closing.
