### ISSUE TITLE
syntax error near unexpected token `JACK,' when running ./configure

### ISSUE THREAD

**Issue by xtrinch** [rncbc/qtractor#55]
I get this when I try to run configure:

> ./configure: line 5156: syntax error near unexpected token `JACK,'
> ./configure: line 5156: `PKG_CHECK_MODULES(JACK, jack >= 0.100.0, ac_libjack="yes", ac_libjack="no")'

I generated the configure file with autoconf:

> x@x:~$ autoconf --version
> autoconf (GNU Autoconf) 2.69

> x@x:~$ qjackctl --version
> Qt: 5.5.1
> QjackCtl: 0.4.2

> x@x:~$ jack --version
> This is jack 3.1.1 (C)2004 Arne Zellentin <zarne@users.sf.net>

Any ideas?

**Comment by trebmuh** [comment]
Did you installed the jack-dev package on your distribution (which one is it by the way) ?

Also, `jack --version` isn't what you want. The one you want is `jackd --version`.

**Comment by xtrinch** [comment]
> x@x:~$ jackd --version
> jackdmp 1.9.11

It's Ubuntu 16.04.1.

I cannot find any jack-dev packages via apt.

**Comment by rncbc** [comment]
you certainly need pkg-config first of all, then libjack-dev
and so on...
-- 
rncbc aka. Rui Nuno Capela
rncbc@rncbc.org
