### ISSUE TITLE
Guitarix Plugins display issue

### ISSUE THREAD

**Issue by Gimmeapill** [rncbc/qtractor#62]
Hello Rui,

A small display issue to report:

Qtractor git (Version: 0.8.0.69git.e8b1d5).
qt5.8.0
Fluxbox
Arch Linux 64
Guitarix git

A double window pop up when opening the plugin GUI. That seems to happen mostly with GxAmplifier-X. Doesn't happen in Ardour, or apparently in Qtractor 0.7.9.

The issue was reported to Guitarix devs below:
http://guitarix.sourceforge.net/forum/viewtopic.php?f=6&t=4803

BR,

LX

**Comment by rncbc** [comment]
check your installed libSUIL version; also look into your qtractor configure log and check whether LV2 UI native GTK2 support is linked in;

you also say that other guitarix plugin GUIs doesn't show the same ghost window, so why you inferred it's solely a qtractor issue? maybe that gxamplifier-x GUI has something special that makes it behave differently in regard to window manager and/or to Gtk2 toolkit?

cheers

**Comment by rncbc** [comment]
issue is not reproduced here (openSUSE Tumbleweed, KDE Plasma: 5.9, Qt: 5.7.1, Qtractor: 0.8.0.71git.fa01a1, libsuil-gtk2-in-qt5: 0.8.4); evidence follows:

![qtractor-gxamplifier_x-1](https://cloud.githubusercontent.com/assets/1554353/22899617/5791580c-f223-11e6-8465-2cbc3c8b6ebc.png)

cheers

**Comment by Gimmeapill** [comment]
Thanks for double checking.
On Arch, suil is at 0.8.2 (which is apparently outdated) with qt at 5.8.0
The config log is also not 100% clean, but the GTK2 check seems to succeed:

```
configure:7966: checking for LV2 UI GTK2 support (libsuil_gtk2_in_qt5)
configure:7989: g++ -o conftest -march=native -O2 -pipe -D__cdecl= -msse -mfpmath=sse -ffast-math -I/usr/include/qt -fPIC -D_FORTIFY_SOURCE=2  -I/usr/include/lilv-0 -I/usr/include/sratom-0 -I/usr/include/sord-0 -I/usr/include/serd-0 -I/usr/include/suil-0 -Isrc/vestige -Isrc/lv2 -Wl,-O1,--sort-common,--as-needed,-z,relro conftest.cpp -lXext -lX11 -lm -L/usr/lib  -ljack -lpthread -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lsuil-0 >&5
configure:7989: $? = 0
```
Full log attached:
[config.txt](https://github.com/rncbc/qtractor/files/772334/config.txt)

Actually there's probably a known issue on Arch as I have just tried the Qtractor official package (0.8.0), and it is built without LV2 Plug-in UI GTK2 native support.

**Comment by rncbc** [comment]
in fact the GTK2 check do NOT succeed (exit status != 0):
```
configure:7966: checking for LV2 UI GTK2 support (libsuil_gtk2_in_qt5)
configure:7989: g++ -o conftest -march=native -O2 -pipe -D__cdecl= -msse -mfpmath=sse -ffast-math -I/usr/include/qt -fPIC -D_FORTIFY_SOURCE=2  -I/usr/include/lilv-0 -I/usr/include/sratom-0 -I/usr/include/sord-0 -I/usr/include/serd-0 -I/usr/include/suil-0 -Isrc/vestige -Isrc/lv2 -Wl,-O1,--sort-common,--as-needed,-z,relro conftest.cpp -lXext -lX11 -lm -L/usr/lib  -ljack -lpthread -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lsuil-0 >&5
configure:7989: $? = 0
configure:7989: ./conftest
configure:7989: $? = 1
configure: program exited with status 1
```
this is all due to outdated and/or non-existant libsuil_gtk2_in_qt5: you need libsuil >= 0.8.4 to succeed.

byee

**Comment by Gimmeapill** [comment]
ok, thanks for the investigation

**Comment by Gimmeapill** [comment]
And I can confirm that ugrading suil to 0.8.5 (latest git) fixes the dispay issue
