### ISSUE TITLE
mixing with synth plugins - no volume change

### ISSUE THREAD

**Issue by rghvdberg** [rncbc/qtractor#7]
When using a midi track with synth plug-in (helm lv2 in this case) changing the volume fader does not change to output volume of the track.
Don't know if this is intended behaviour or plug-in specific.

**Comment by rncbc** [comment]
On 12/29/2015 01:18 PM, rghvdberg wrote:
> When using a midi track with synth plug-in (helm lv2 in this case)
> changing the volume fader does not change to output volume of the track
> Don't know if this is intended behaviour or plug-in specific
>

it's plugin specific.

the MIDI track volume fader applies to midi channel volume (CC#7), not 
to audio output.

in qtractor sequencer model (old-school GM, i know) it's responsibility 
of a MIDI plugin instrument, or outboard sound generator module or synth 
for that matter, to *react* accordingly to CC#7 for audio output volume 
(and CC#10 for audio panning btw.)

hth.
cheers
-- 
rncbc aka. Rui Nuno Capela

**Comment by rghvdberg** [comment]
that makes sense :-)

**Comment by rghvdberg** [comment]
succes !
assigned ctrl #7 to the volume in Helm (via midi learning)
works perfect
closing this
