### ISSUE TITLE
losing lv2 atoms sent to ui

### ISSUE THREAD

**Issue by jmage619** [rncbc/qtractor#72]
I found a similar issue to
https://github.com/rncbc/qtractor/issues/71

but this time its for sending an atom sequence to the UI from the plugin, into the port_event callback.

Again I think the behavior is best illustrated with a test plugin:
https://github.com/jmage619/test_atom.lv2

When activated, my test is simulating how my work-in-progress sampler updates the UI for each wav "zone" that is loaded from reading a patch. I send the UI a bunch of meta info, such as start, end time, loop points, wav path, etc, so each zone has an atom sent over to tell the gui to fill a row with the relevant controls.

Note that the test sends 42 atoms (here just strings for simplicity), each is 472 bytes.  It looks like my notify port size is 20480 in qtractor, and the total sequence built is 20176, so there should be enough space to hold them all.

However on the receiving end the UI only receives 2 atoms. 472 * 3 is greater than 1024, so I suspect maybe a 1k ring buffer is somewhere in between?  If that's the case, wouldn't it make sense to make this large enough to hold the full 20k bytes available in the control port?

I do plan to significantly reduce the 472 atom sizes, I was playing around with just passing a pointer inside an atom long. But in any case it looks like there's an unexpected 1k limit somewhere here preventing the full 20k bytes of control port from being passed to the UI.

Below is a sample output of a run.

```
UI: ui instantiate called
plugin activated!
PLUGIN: get zones received!!
PLUGIN: notify capacity: 20480
PLUGIN: sent addZone 0; obj size: 472
PLUGIN: sent addZone 1; obj size: 472
PLUGIN: sent addZone 2; obj size: 472
PLUGIN: sent addZone 3; obj size: 472
PLUGIN: sent addZone 4; obj size: 472
PLUGIN: sent addZone 5; obj size: 472
PLUGIN: sent addZone 6; obj size: 472
PLUGIN: sent addZone 7; obj size: 472
PLUGIN: sent addZone 8; obj size: 472
PLUGIN: sent addZone 9; obj size: 472
PLUGIN: sent addZone 10; obj size: 472
PLUGIN: sent addZone 11; obj size: 472
PLUGIN: sent addZone 12; obj size: 472
PLUGIN: sent addZone 13; obj size: 472
PLUGIN: sent addZone 14; obj size: 472
PLUGIN: sent addZone 15; obj size: 472
PLUGIN: sent addZone 16; obj size: 472
PLUGIN: sent addZone 17; obj size: 472
PLUGIN: sent addZone 18; obj size: 472
PLUGIN: sent addZone 19; obj size: 472
PLUGIN: sent addZone 20; obj size: 472
PLUGIN: sent addZone 21; obj size: 472
PLUGIN: sent addZone 22; obj size: 472
PLUGIN: sent addZone 23; obj size: 472
PLUGIN: sent addZone 24; obj size: 472
PLUGIN: sent addZone 25; obj size: 472
PLUGIN: sent addZone 26; obj size: 472
PLUGIN: sent addZone 27; obj size: 472
PLUGIN: sent addZone 28; obj size: 472
PLUGIN: sent addZone 29; obj size: 472
PLUGIN: sent addZone 30; obj size: 472
PLUGIN: sent addZone 31; obj size: 472
PLUGIN: sent addZone 32; obj size: 472
PLUGIN: sent addZone 33; obj size: 472
PLUGIN: sent addZone 34; obj size: 472
PLUGIN: sent addZone 35; obj size: 472
PLUGIN: sent addZone 36; obj size: 472
PLUGIN: sent addZone 37; obj size: 472
PLUGIN: sent addZone 38; obj size: 472
PLUGIN: sent addZone 39; obj size: 472
PLUGIN: sent addZone 40; obj size: 472
PLUGIN: sent addZone 41; obj size: 472
PLUGIN: total seq size: 20176
UI: received add zone!! zone 0
UI: received add zone!! zone 1
```

**Comment by rncbc** [comment]
according to LV2 spec, you must the declare and use of [LV2 Resize Port](http://lv2plug.in/ns/ext/resize-port/) extension, setting a suitable [minimumSIze](http://lv2plug.in/ns/ext/resize-port/#minimumSize) property for each atom port involved.

so to close this issue, it's a matter of adding some `rsz:minimumSize 20480 ;` to the respective atom ports declarations on the plugin's .ttl -- qtractor and any other LV2 host for that matter will then allocate its ring-buffers to suitable sizes.

**Comment by jmage619** [comment]
Yes, this solved my issue. I don't think I ever would have figured this out, but I blame the cryptic LV2 spec, not the host implementation :)

Thank you, and sorry for the noise!
