### ISSUE TITLE
Possibility to use hybrid plugins on a bus

### ISSUE THREAD

**Issue by milasudril** [rncbc/qtractor#76]
Is it possible to connect MIDI to audio filters, that are accepts MIDI input (vocoders, MIDI controlled filters) in qtractor? If not, that would be a great improvement.

**Comment by rncbc** [comment]
only MIDI tracks and buses do convey MIDI data *and* audio; audio tracks or buses deal with audio and only audio; you may work with either audio or MIDI Inserts, Aux-sends pseudo-plugins that let you route, send/return externally (inserts) and fork internally (aux-sends) the audio or MIDI signal around.

**Comment by milasudril** [comment]
Maybe I should add a figure that illustrates the scenario:

                      +--------+
      MIDI track----->|        |
                      | Filter |----->Audio bus
      Audio track---->|        |
                      +--------+

I guess that this is not possible without loading the plugin in an external host, since this would require placing audio data on a MIDI track
