### ISSUE TITLE
Feature request: Clip panning

### ISSUE THREAD

**Issue by thebutant** [rncbc/qtractor#77]
This feature is not a very big deal, but I have still been wanting it a number of times.
The idea is this:

When double clicking a clip on the timeline, you get quite a few possibilities, like stretching, pitch shifting and gain control. I think it would be really handy if you could also get the option of panning. That way you could easily make simple stereo effects without automation. Or even have two clips on the same track with the same plugins, but hear one of them to the left and the other one to the right.

It would also make a difference in chronology: When panning the track, the panning comes last in the mix chain. If you could pan the clip in itself, then the panning would come first, and the plugins would still be in normal stereo mode.

To avoid any doubt: Oh, yes I do love Qtractor without this feature aswell.

**Comment by rncbc** [comment]
that's one (hell of) an idea

question is: is it acceptable to make it a static property of an audio clip (as time-stretch and pitch-shift are) or are  you proposing to make it _automatable_, which i'm afraid won't be anytime soon or rather not before v2 ? :)

cheers

**Comment by thebutant** [comment]
My idea was to have it exactly like time-stretch, pitch-shift and gain: 
Static, not automatable.

And just like the others: If you copy the clip and paste it somewhere else, you can change the panning of this new one.

When automation is needed, there are already plenty of ways to do that (both with automating track panning and using stereo/balance plugins). 

This idea is just meant as an easy way of panning a clip, saving the user from automation, plugins or panning the whole track.

**Comment by rncbc** [comment]
guess what? it's done, see  latest git head master (873275b5c45b55def1e2201078201ac54c7adbfd onwards....)

cheers

**Comment by thebutant** [comment]
Wow!
There are plenty of reasons why I love Qtractor. 
But your friendliness and attitude towards us users is really one of the dearest.

Thank you so much!
