### ISSUE TITLE
4 Band Parametric EQ Stereo on midi track (with plug-in instrument) crashes Qtractor

### ISSUE THREAD

**Issue by rghvdberg** [rncbc/qtractor#8]
Latest qtractor 

> dpkg -l | grep qtractor
> ii  qtractor                                    2:0.7.3-1kxstudio1                                  amd64        MIDI/Audio multi-track sequencer application
> ii  qtractor-dbg                                2:0.7.3-1kxstudio1                                  amd64        Debugging symbols for Qtractor

Audio tracks are fine

**Comment by rncbc** [comment]
which plugin? LV2 URI?

**Comment by rghvdberg** [comment]
http://gareus.org/oss/lv2/fil4#stereo

**Comment by rncbc** [comment]
On 01/06/2016 08:25 AM, rghvdberg wrote:
> http://gareus.org/oss/lv2/fil4#stereo
>

works fine here, both ways audio or MIDI track insert (qtractor v0.7.3, 
qt5.5.1, openSUSE Tumbleweed).

cheers
-- 
rncbc aka. Rui Nuno Capela

**Comment by rghvdberg** [comment]
got a backtrace
http://pastebin.com/HdS6NmzM
hope this helps or at least figure out if it's a qtractor  / kxstudio / plugin

**Comment by rncbc** [comment]
On 01/06/2016 08:58 AM, rghvdberg wrote:
> got a backtrace
> http://pastebin.com/HdS6NmzM
> hope this helps or at least figure out if it's a qtractor / kxstudio /
> plugin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rncbc/qtractor/issues/8#issuecomment-169270424>.
>

see this?

#4 0x00007fffb9e1e6be in ?? () from /usr/lib/lv2/helm.lv2/helm.so

the crash is under helm's watch, not qtractor's.

you ought to get helm debugging symbols as well, and thus, report the 
issue to mtytel [1] as well (if it's the pristine same code base)

[1] https://github.com/mtytel/helm

hth.
cheers
-- 
rncbc aka. Rui Nuno Capela

**Comment by rghvdberg** [comment]
mmm same crash happends with Zyn as plugin
will test more with other plugins as soundsource

**Comment by rncbc** [comment]
On 01/10/2016 09:00 AM, rghvdberg wrote:
> mmm same crash happends with Zyn as plugin
> will test more with other plugins as soundsource
>

which zyn(addsubfx.lv2 i suppose) URI?

afaict. there's at least a couple out there, one from carla-git and 
another from fundamental/zynaddsubfx dpf-plugin branch, both from 
kxstudio/falktx. also, they are both still and ever in a development 
flux phase, so please report your findings to upstream

hth.
cheers
-- 
rncbc aka. Rui Nuno Capela
