### ISSUE TITLE
fabla presets are not found 

### ISSUE THREAD

**Issue by ycollet** [rncbc/qtractor#9]
I use qtractor from git repo on fedora 23.
I loaded the fabla plugin on a track. When I open the gui, the fabla presets are not found.
I loaded the same plugin on ardour and here, it works fine.

**Comment by rncbc** [comment]
On 01/06/2016 07:24 AM, ycollet wrote:
> I use qtractor from git repo on fedora 23
> I loaded the fabla plugin on a track When I open the gui, the fabla
> presets are not found
> I loaded the same plugin on ardour and here, it works fine
>

LV2 presets are accessible from the plugins properties widget (aka. 
generic UI dialog) or directly from plugins context-menu.

have you looked into these?

hth.
cheers
-- 
rncbc aka. Rui Nuno Capela

**Comment by ycollet** [comment]
Yes, I tried to load the preset via the fabla gui.
I done the same thing under ardour and the presets where accessible via the fabla gui.

----- Mail original -----
De: "Rui Nuno Capela" <notifications@github.com>
À: "rncbc/qtractor" <qtractor@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>
Envoyé: Mercredi 6 Janvier 2016 09:25:40
Objet: Re: [qtractor] fabla presets are not found  (#9)

On 01/06/2016 07:24 AM, ycollet wrote: 
> I use qtractor from git repo on fedora 23 
> I loaded the fabla plugin on a track When I open the gui, the fabla 
> presets are not found 
> I loaded the same plugin on ardour and here, it works fine 
> 

LV2 presets are accessible from the plugins properties widget (aka. 
generic UI dialog) or directly from plugins context-menu. 

have you looked into these? 

hth. 
cheers 
-- 
rncbc aka. Rui Nuno Capela

**Comment by rncbc** [comment]
On 01/06/2016 09:27 AM, ycollet wrote:
> Yes, I tried to load the preset via the fabla gui.
> I done the same thing under ardour and the presets where accessible via
> the fabla gui.
>

the fabla gui does not give you access to lv2 presets on is own.
what happens on ardour is that the fabla gui is embedded on an ardour 
window and it is the later that gives you access to the lv2 preset list 
as same as on qtractor's plugin properties/generic UI.

hth.
-- 
rncbc aka. Rui Nuno Capela

**Comment by ycollet** [comment]
I have no presets on the qtractor plugin properties/generic ui.
I have tried all the combination on the properties/generic ui, but no 
presets appear.

Here is the content of /usr/lib64/lv2 for the fabla plugin:

$ ls /usr/lib64/lv2/fabla
fabla808.lv2/
fablaHardElectro.lv2/
fablaSavageDrums.lv2/
fablaEasternHop.lv2/
fabla.lv2/

**Comment by ycollet** [comment]
The configure command I use for qtractor compilation:

./configure --prefix=/local/stow/qtractor-devel --enable-lv2-event 
--enable-debug

**Comment by ycollet** [comment]
And the results:

   Qtractor 0.7.1.18

   Build target . . . . . . . . . . . . . . . . . . .: debug

   JACK Audio Connection Kit support  . . . . . . . .: yes
   ALSA MIDI Sequencer support  . . . . . . . . . . .: yes
   General audio file support (libsndfile)  . . . . .: yes
   Ogg Vorbis audio file support (libvorbis)  . . . .: yes
   MPEG-1 Audio Layer 3 file support (libmad) . . . .: yes
   Sample-rate conversion support (libsamplerate) . .: yes
   Pitch-shifting support (librubberband) . . . . . .: yes
   OSC service support (liblo)  . . . . . . . . . . .: yes
   Archive/Zip file support (zlib)  . . . . . . . . .: yes
   IEEE 32bit float optimizations . . . . . . . . . .: yes
   SSE optimization support (x86) . . . . . . . . . .: yes
   LADSPA plug-in support . . . . . . . . . . . . . .: yes
   DSSI plug-in support . . . . . . . . . . . . . . .: yes
   VST plug-in support  . . . . . . . . . . . . . . .: yes
   LV2 plug-in support  . . . . . . . . . . . . . . .: yes
   LV2 plug-in UI support . . . . . . . . . . . . . .: yes
   LV2 plug-in External UI support  . . . . . . . . .: yes
   LV2 plug-in MIDI/Event support (DEPRECATED)  . . .: yes
   LV2 plug-in MIDI/Atom support  . . . . . . . . . .: yes
   LV2 plug-in Worker/Schedule support  . . . . . . .: yes
   LV2 plug-in State support  . . . . . . . . . . . .: yes
   LV2 plug-in State Files support  . . . . . . . . .: yes
   LV2 plug-in Programs support . . . . . . . . . . .: yes
   LV2 plug-in Presets support  . . . . . . . . . . .: yes
   LV2 plug-in Time support . . . . . . . . . . . . .: yes
   LV2 plug-in Time/position support  . . . . . . . .: yes
   LV2 plug-in Options support  . . . . . . . . . . .: yes
   LV2 plug-in Buf-size support . . . . . . . . . . .: yes
   LV2 plug-in UI Idle interface support  . . . . . .: yes
   LV2 plug-in UI Show interface support  . . . . . .: yes
   LV2 plug-in UI GTK2 native support . . . . . . . .: yes
   LV2 plug-in UI X11 native support  . . . . . . . .: yes

   JACK Session support . . . . . . . . . . . . . . .: yes
   JACK Latency support . . . . . . . . . . . . . . .: yes
   JACK Metadata support  . . . . . . . . . . . . . .: yes

   Non Session Management (NSM) support . . . . . . .: yes

   X11 Unique/Single instance . . . . . . . . . . . .: no
   VeSTige header support . . . . . . . . . . . . . .: yes
   Gradient eye-candy . . . . . . . . . . . . . . . .: yes
   Debugger stack-trace (gdb) . . . . . . . . . . . .: yes

   Install prefix . . . . . . . . . . . . . . . . . .: 
/local/stow/qtractor-devel

Now type 'make', followed by 'make install' as root.

**Comment by rncbc** [comment]
On 01/06/2016 07:16 PM, ycollet wrote:
> I have no presets on the qtractor plugin properties/generic ui.
> I have tried all the combination on the properties/generic ui, but no
> presets appear.
>
> Here is the content of /usr/lib64/lv2 for the fabla plugin:
>
> $ ls /usr/lib64/lv2/fabla
> fabla808.lv2/
> fablaHardElectro.lv2/
> fablaSavageDrums.lv2/
> fablaEasternHop.lv2/
> fabla.lv2/
>

exactly the ones that should appear on the drop-down list on the plugin 
properties/generic UI (and context-menu as well).

something's fishy... which (lib)lilv version?

besides ardour, have you tried jalv.(gtk|qt) ?
-- 
rncbc aka. Rui Nuno Capela

**Comment by ycollet** [comment]
I just tested with jalv:

$ jalv.qt http://www.openavproductions.com/fabla

The last lines in  the console:

pad_release_16       = 0,500000
Preset: file:///usr/lib64/lv2/fabla808.lv2/fabla808.ttl
Preset: file:///usr/lib64/lv2/fablaEasternHop.lv2/fablaEasternHop.ttl
Preset: file:///usr/lib64/lv2/fablaHardElectro.lv2/fablaHardElectro.ttl
Preset: file:///usr/lib64/lv2/fablaSavageDrums.lv2/fablaSavageDrums.ttl

And the version of lilv:

$ dnf info lilv
Vérification de l'expiration des métadonnées effectuée il y a 1 day, 
15:59:27 sur Tue Jan  5 06:21:11 2016.
Paquets installés
Nom         : lilv
Architectur : x86_64
Époque      : 0
Version     : 0.20.0
Révision    : 4.fc23
Taille      : 153 k
Dépôt       : @System
Depuis le d : @commandline
Résumé      : An LV2 Resource Description Framework Library
URL         : http://drobilla.net/software/lilv/
Licence     : MIT
Description : lilv is a library to make the use of LV2 plugins as simple 
as possible
             : for applications. Lilv is the successor to SLV2, 
rewritten to be significantly
             : faster and have minimal dependencies.

**Comment by rncbc** [comment]
evidence attached (screenshot)
![qtractor-fabla-presets-1](https://cloud.githubusercontent.com/assets/1554353/12157762/07fc79c4-b4cc-11e5-8b30-bf26af865f20.png)

**Comment by ycollet** [comment]
How do you got the second Window ? (the other one than the fabla gui) ?

**Comment by rncbc** [comment]
On 2016-01-07 06:34, ycollet wrote:
> How do you got the second Window ? (the other one than the fabla gui)
> ?
> 

nothing but the old plugin/Properties... generic UI window that i've 
referring you to all this time.

byee
-- 
rncbc aka. Rui Nuno Capela

**Comment by rncbc** [comment]
ah, and don't forget the other option as from plugin-context-menu/Preset, also mentioned before:
![qtractor-fabla-presets-2](https://cloud.githubusercontent.com/assets/1554353/12174854/f628430a-b556-11e5-8dc9-c5c0eca1eeeb.png)

**Comment by ycollet** [comment]
I can see the presets that way, but I am not able to see the other GUI.
When I check one preset, nothing happens. If I click on all notes, no sound is emitted. Like if the preset has not been selected.


----- Mail original -----
De: "Rui Nuno Capela" <notifications@github.com>
À: "rncbc/qtractor" <qtractor@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>
Envoyé: Jeudi 7 Janvier 2016 16:55:04
Objet: Re: [qtractor] fabla presets are not found  (#9)



ah, and don't forget the other option as from plugin-context-menu/Preset, also mentioned before: 
qtractor-fabla-presets-2

**Comment by ycollet** [comment]
OK, finally, via this menu, the presets works.
I just still not able to get the Properties GUI.

**Comment by ycollet** [comment]
And I found the Properties GUI.
Thanks.
Sorry for all that.

**Comment by ycollet** [comment]
I am now able to load a preset, but the the presets doesn't shows up on the first folder on the add a new track gui.

**Comment by rncbc** [comment]
On 2016-01-08 08:18, ycollet wrote:
> I am now able to load a preset, but the the presets doesn't shows up
> on the first folder on the add a new track gui.
> 

what first folder? you mean MIDI track properties instrument, bank, 
programs?

nope. plugin presets and instrument programs are not the same thing, 
although related: a preset eventually provides one or more addressable 
banks/programs but speaking of the lv2_programs extension, it's not 
official nor implemented on most plugins out there--it's also 
non-compliant with the current lv2 spec, so chances are it won't get 
ever.

hth.
cheers
-- 
rncbc aka. Rui Nuno Capela

**Comment by ycollet** [comment]
Yes I was talking about this folder.
I was not aware of this difference between instrument program and plugin presets ... Sorry :)
So, I think I / you can close this "bug".

YC

----- Mail original -----
De: "Rui Nuno Capela" <notifications@github.com>
À: "rncbc/qtractor" <qtractor@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>
Envoyé: Vendredi 8 Janvier 2016 09:43:54
Objet: Re: [qtractor] fabla presets are not found  (#9)

On 2016-01-08 08:18, ycollet wrote: 
> I am now able to load a preset, but the the presets doesn't shows up 
> on the first folder on the add a new track gui. 
> 

what first folder? you mean MIDI track properties instrument, bank, 
programs? 

nope. plugin presets and instrument programs are not the same thing, 
although related: a preset eventually provides one or more addressable 
banks/programs but speaking of the lv2_programs extension, it's not 
official nor implemented on most plugins out there--it's also 
non-compliant with the current lv2 spec, so chances are it won't get 
ever. 

hth. 
cheers 
-- 
rncbc aka. Rui Nuno Capela
